force-app/main/default/objects/Country__mdt/fields/COU_PCK_ISO_Code2__c.field-meta.xml
<CustomField>
    <fullName>COU_PCK_ISO_Code2__c</fullName>
    <description>Country ISO aplha code 2</description>
    <label>ISO Code 2</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AQ</fullName>
            </value>
            <value>
                <fullName>TF</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BJ</fullName>
            </value>
            <value>
                <fullName>CS</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BS</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>GJ</fullName>
            </value>
            <value>
                <fullName>BY</fullName>
            </value>
            <value>
                <fullName>BZ</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__mdt/fields/COU_PCK_Name__c.field-meta.xml
<CustomField>
    <fullName>COU_PCK_Name__c</fullName>
    <label>Picklist value name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Oceania</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>American Virgin Islands</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbados</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Australian Oceania</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrein</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermudas</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bielorussia</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia - Herzegovina</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CNT_B2B_Create_Beneficiary.cls
public with sharing class CNT_B2B_Create_Beneficiary {

    /*
    Author:         Quesada
    Company:        Deloitte
    Description:    Gets the country picklist value from account IBAN code
    History:
    <Date>          <Author>            <Description>
    12/2020         Quesada             Initial version
    */
    @AuraEnabled
    public static String initCountryValues (String searchedString) {
        System.debug('searchedString: ' + searchedString);
        Map<String, String> isoCodeValue = new Map<String, String>();
        String picklistValue = null;
        if (searchedString != null) {
            String code = searchedString.substring(0, 2);
            System.debug('code: ' + code);
            List<Country__mdt> countries = new List<Country__mdt>([
                SELECT Id, COU_PCK_ISO_Code2__c, COU_PCK_Name__c
                FROM Country__mdt
            ]);
            System.debug('countries.isEmpty(): ' + countries.isEmpty());
            if (!countries.isEmpty()) {
                for (Country__mdt cmdt : countries) {
                    isoCodeValue.put(cmdt.COU_PCK_ISO_Code2__c, cmdt.COU_PCK_Name__c);
                }
                picklistValue = isoCodeValue.get(code);
                System.debug('picklistValue: ' + picklistValue);
            }
        }
        return picklistValue;
    }
}