force-app/main/default/objects/Notification_Redirect__c/Notification_Redirect__c.object-meta.xml
<CustomObject>
    <label>Notification Redirect</label>
    <nameField>
        <displayFormat>NR-{00000000}</displayFormat>
        <label>Notification Redirect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications Redirect</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Redirect__c/fields/Delete_date__c.field-meta.xml
<CustomField>
    <fullName>Delete_date__c</fullName>
    <formula>CreatedDate + 90</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delete date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DeleteNotificationsBatch.cls
/*----------------------------------------------------------------------------------
Author:         Antonio Duarte
Company:        Deloitte
Description:    Batch that deletes the old notification redirect records 
TestClass:		DeleteNotificationsSchedulable_Test
History
<Date>			<Author>			<Description>
05/10/2020		Antonio Duarte     	Initial version
----------------------------------------------------------------------------------*/
global class DeleteNotificationsBatch implements Database.Batchable<sObject>{
    global DeleteNotificationsBatch(){
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([
            SELECT Id
            FROM Notification_Redirect__c
            WHERE Delete_date__c <= TODAY
        ]);
    }
    
    global void execute(Database.BatchableContext BC, List<Notification_Redirect__c>scope){
        delete scope;
    }
    
    global void finish(Database.BatchableContext BC){
    }
}