zip/mdapiOTVLwr/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CASE_PCK_Beneficiary_country__c</fullName>
        <label>Beneficiary country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_ISO_aplha_code_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CASE_PCK_OrderingCountry__c</fullName>
        <label>Ordering Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_ISO_aplha_code_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CASE_PCK_Record_Type__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case RecordType</fullName>
                </value>
                <value>
                    <fullName>Payment Parent Case</fullName>
                </value>
                <value>
                    <fullName>Payment Child Case</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Payment Case</fullName>
                    <isActive>false</isActive>
                    <label>Payment Case</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CASE_PCK_Sourcesystem__c</fullName>
        <label>Source system</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
                <value>
                    <fullName>Mulesoft</fullName>
                </value>
                <value>
                    <fullName>Stratio</fullName>
                </value>
                <value>
                    <fullName>GTS Core</fullName>
                </value>
                <value>
                    <fullName>VAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CASE_affected_functionality__c</fullName>
        <label>Affected functionality</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global_Balance</fullName>
                    <label>Global Balance</label>
                </value>
                <value>
                    <fullName>International_Payment_Tracker</fullName>
                    <label>International Payment Tracker</label>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                    <default>true</default>
                    <label>Others</label>
                </value>
                <value>
                    <fullName>Payments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Country_ISO_aplha_code_2.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AS</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <masterLabel>Country ISO aplha code 2</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HANDLER_Case_Test.cls
@isTest
private class HANDLER_Case_Test {
    
    @testSetup static void setup(){
        //Create common test users
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User usr1 = new User(Alias = 'standt', Email='standarduser1@desan.com', 
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = p.Id, 
                            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser1@desan.com');
        insert usr1 ;
        User usr2 = new User(Alias = 'standt', Email='standarduser2@desan.com', 
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = p.Id, 
                            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser2@desan.com');
        insert usr2;
        // Create common test cases
        list<case> oldCases = new list<case>();
        list<case> newCases = new list<case>();
        
        for(Integer i=0; i<3; i++){
            oldCases.add(new case(OwnerId = usr1.Id, Priority = 'High', CASE_affected_functionality__c = 'International_Payment_Tracker', Status = 'New', Origin = 'Internal', CASE_PCK_Record_Type__c= 'Case RecordType', Subject = 'oldCase'+ i));
            newCases.add(new case(OwnerId = usr2.Id, Priority = 'High', CASE_affected_functionality__c = 'International_Payment_Tracker', Status = 'CAU1', Origin = 'Internal',CASE_PCK_Record_Type__c= 'Case RecordType', Subject = 'newCase'+ i));
            oldCases.add(new case(OwnerId = usr1.Id, Priority = 'Low', CASE_affected_functionality__c = 'International_Payment_Tracker', Status = 'New', Origin = 'Internal', CASE_PCK_Record_Type__c= 'Payment Parent Case', CASE_PCK_Sourcesystem__c = 'Mulesoft', CASE_PCK_OrderingCountry__c = 'ES', Subject = 'oldCase'+ i));
            newCases.add(new case(OwnerId = usr2.Id, Priority = 'Low', CASE_affected_functionality__c = 'International_Payment_Tracker', Status = 'CAU1', Origin = 'Internal',CASE_PCK_Record_Type__c= 'Payment Child Case', CASE_PCK_Sourcesystem__c = 'Salesforce', CASE_PCK_Beneficiary_country__c='ES', CASE_PCK_OrderingCountry__c = 'ES', Subject = 'newCase'+ i));
        }
        insert oldCases;
        insert newCases;
        
        case cs = new case(OwnerId = usr2.Id, Priority = 'High', CASE_affected_functionality__c = 'International_Payment_Tracker', Status = 'Closed Solved', Origin = 'Internal', Subject = 'closed case');
        insert cs;
        task tsk = new task(OwnerId = usr2.Id, WhatId = cs.id, Priority = 'High');
        insert tsk;
        
        case itCs = new case(OwnerId = usr2.Id, Priority = 'High', CASE_affected_functionality__c = 'International_Payment_Tracker', Status = 'IT', Origin = 'Internal', Subject = 'IT case');
        insert itCs;
        
        case afterUpdateOwner = new case(OwnerId = usr1.Id, Priority = 'High', CASE_affected_functionality__c = 'International_Payment_Tracker', Status = 'In progress', Origin = 'Internal', CASE_PCK_Record_Type__c= 'Case RecordType', Subject = 'updateOwner');       
        insert afterUpdateOwner;

        
    }
    
    @isTest static void createTaskTest(){
        
        list<case> oldCases = [select id, ownerId, Priority, CASE_affected_functionality__c, CaseNumber, Status, Origin, Subject from case where Subject =: 'oldCase0' limit 1];
        list<case> newCases = [select id, ownerId, Priority, CASE_affected_functionality__c, CaseNumber, Status, Origin, Subject from case where Subject =: 'newCase0' limit 1]; 
        HANDLER_Case.createTask(oldCases, newCases);
        list<task> tsk = [select id, Subject from task where WhatId =: newCases.get(0).id];
        system.assert(tsk.size() >  0, 'ERROR');
        
    }
    
    @isTest static void deleteRelatedTasks(){
        
        list<case> myCases = [select id, ownerId, Priority, CASE_affected_functionality__c, CaseNumber, Status, Origin, Subject, IsClosed from case where Subject =: 'closed case' limit 1];
		HANDLER_Case.deleteRelatedTasks(myCases);  
        
    }
    
    @isTest static void updateMilestoneCaseTest(){
        
        list<case> myCases = [select id, ownerId, Priority, CASE_affected_functionality__c, CaseNumber, Status, Origin, Subject, IsClosed from case where Subject =: 'closed case' limit 1];
		HANDLER_Case.updateMilestoneCase(myCases); 
        
    }
    
    @isTest static void fillBasicFieldsTest(){
        
    }
    
   @isTest static void updateOwnerTest(){
        Case caseRecord = [select id, ownerId, Priority, CASE_affected_functionality__c, CaseNumber, Status, Origin, Subject from case where  Status = 'In progress' and Subject = 'updateOwner' limit 1];
       	caseRecord.status = 'CAU1';
       	update caseRecord;
     
        
    }
    
    @isTest static void stopMilestoneTest(){
        
        list<case> itCases = [select id, ownerId, Priority, CASE_affected_functionality__c, CaseNumber, Status, Origin, Subject, CreatedById from case];
        HANDLER_Case.stopMilestone(itCases);
        
    }
 
    @isTest
    static void createComplianceCaseTest(){
        WRAPPER_AccountList.AccountDetails accData = new WRAPPER_AccountList.AccountDetails();
        ReturnValue rv = HANDLER_Case.createComplianceCase('PaymentId', 'Description', accData, accData); 
    }
    
    @isTest
    static void TreasuryUpdatesTest(){
        User treasurer = [SELECT Id FROM User WHERE Profile.Name = 'Treasury' AND isActive = true LIMIT 1 ];
        User integration = [SELECT Id FROM User WHERE Profile.Name = 'Integration' AND isActive = true LIMIT 1];
        
        Case objCase = new Case (
            Type = 'Funding Back',
            CASE_PCK_Record_Type__c = 'Treasury',
            Status = 'New');
        
        Case objCase2 = new Case (
            Type = 'Notification',
            CASE_PCK_Record_Type__c = 'Treasury',
            Status = 'New');
        
        Test.startTest();
        insert objCase2;
        system.runAs(treasurer){
            insert objCase;
        	objCase.status = 'Pending of Authorization';
        	update objCase;
        }
        system.runAs(integration){
        	objCase.status = 'Closed Solved';
        	update objCase;
        }
        objCase.status = 'Closed Cancelled';
        objCase.CASE_TXT_cancelledReason__c = 'TestReason';
        update objCase;
        Test.stopTest();
    }
    
}