zip/mdapiOTVLwr/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CASE_affected_functionality__c</fullName>
        <label>Affected functionality</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global_Balance</fullName>
                    <label>Global Balance</label>
                </value>
                <value>
                    <fullName>International_Payment_Tracker</fullName>
                    <label>International Payment Tracker</label>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                    <default>true</default>
                    <label>Others</label>
                </value>
                <value>
                    <fullName>Payments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CNT_PaymentInformationButton_Test.cls
/*----------------------------------------------------------------------------------
Author:         A. Borraz
Company:        Deloitte
History
<Date>			<Author>		<Description>
18/11/2020		A. Borraz     Initial version
----------------------------------------------------------------------------------*/
@isTest
public class CNT_PaymentInformationButton_Test {
	
    @testSetup  
    static void setObjects(){
        Test.startTest();
        system.debug(getCaseDataTest());
        system.debug(getCaseDataTestError());
        system.debug(getPaymentDetailTest());

        Test.stopTest();
    }
   
    @isTest
    static ReturnValue getCaseDataTest(){
        Case c = new Case(suppliedName = 'Test',
                          CASE_affected_functionality__c = 'Others'); 
        insert c;
        return CNT_PaymentInformationButton.getCaseData(c.Id);
    }
    
    @isTest
    static ReturnValue getCaseDataTestError(){
        return CNT_PaymentInformationButton.getCaseData('Test2');
	}
    
    @isTest
    public static ReturnValue getPaymentDetailTest(){
        Payment__c payment = new Payment__c(Name = 'Test'); 
        insert payment;
 		return CNT_PaymentInformationButton.getPaymentDetail(payment.ID);
    }
}