zip/mdapiOTVLwr/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CASE_Analyst__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Analyst Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PaymentCase</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CASE_CAU1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CASE_CAU1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CASE_CHK_ReverseBeneficiaryCredit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reverse beneficiary credit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CASE_DATE_StartDateInProgress__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>StartDateInProgress</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CASE_NUM_DateInprogress__c</fullName>
        <label>TimeInprogress</label>
        <precision>10</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CASE_PCK_Beneficiary_country__c</fullName>
        <label>Beneficiary country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_ISO_aplha_code_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CASE_PCK_Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_ISO_aplha_code_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CASE_PCK_OrderingCountry__c</fullName>
        <label>Ordering Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_ISO_aplha_code_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CASE_PCK_Record_Type__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case RecordType</fullName>
                </value>
                <value>
                    <fullName>Payment Parent Case</fullName>
                </value>
                <value>
                    <fullName>Payment Child Case</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Payment Case</fullName>
                    <isActive>false</isActive>
                    <label>Payment Case</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CASE_PCK_Sourcesystem__c</fullName>
        <label>Source system</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
                <value>
                    <fullName>Mulesoft</fullName>
                </value>
                <value>
                    <fullName>Stratio</fullName>
                </value>
                <value>
                    <fullName>GTS Core</fullName>
                </value>
                <value>
                    <fullName>VAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CASE_Resolutor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resolutor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CASE_Submitter_General__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CASE_TXT_PaymentId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Payment Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CASE_User_Submitter_General__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CASE_affected_functionality__c</fullName>
        <label>Affected functionality</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Global_Balance</fullName>
                    <label>Global Balance</label>
                </value>
                <value>
                    <fullName>International_Payment_Tracker</fullName>
                    <label>International Payment Tracker</label>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                    <default>true</default>
                    <label>Others</label>
                </value>
                <value>
                    <fullName>Payments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Country_ISO_aplha_code_2.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AS</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <masterLabel>Country ISO aplha code 2</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HANDLER_Case.cls
public without sharing class HANDLER_Case {
    
    public static void createTask(List<Case> oldCaseList, List<Case> newCaseList){
        List<Task> taskList = new List<Task>();
      
        for (Case objCase: newCaseList) {
            if (objCase.Status == 'CAU1'){
                if(objCase.OwnerId != oldCaseList[0].OwnerId){              
                        Task newTask = new Task();
                        newTask.OwnerId = objCase.OwnerId;
                        List<String> argument = new List<String>();
                        argument.add(objCase.CaseNumber);
                        String value = String.format(System.Label.Task_Notifaction, argument);
                        newTask.Subject = value;
                        newTask.WhatId = objCase.Id;
                        newTask.Priority = objCase.Priority;
                        taskList.add(newTask);                     
                }            
            }
        
        }
        insert taskList;
    }
    
    public static void AssignRecordType(List<Case> newCaseList){
        RecordType RTC = [Select Name, id, SobjectType from RecordType where Name = 'Case RecordType' and SobjectType  = 'Case' LIMIT 1];
        /*RecordType RTPP = [Select Name, id, SobjectType from RecordType where Name = 'Payment Parent Case' and SobjectType  = 'Case' LIMIT 1];
        RecordType RTPC = [Select Name, id, SobjectType from RecordType where Name = 'Payment Child Case' and SobjectType  = 'Case' LIMIT 1];*/
        
          
        
        for (Case StandardCase: newCaseList){
            if(String.valueOf(StandardCase.OwnerId).startsWith('005')){
                if(StandardCase.CASE_PCK_Record_Type__c == 'Case RecordType'){
                    StandardCase.RecordTypeId = RTC.Id;
                }
            }
            /*else if(StandardCase.CASE_PCK_Record_Type__c == 'Payment Parent Case'){
               
                StandardCase.RecordTypeId = RTPP.Id;
           
                if(StandardCase.CASE_PCK_Sourcesystem__c == 'Mulesoft'){
                    String country = StandardCase.CASE_PCK_OrderingCountry__c;
                    if(country != null && country != ''){
                        country = country + '_PaymentAnalystQueue';
                        List<group> idOwner = new List<group>([SELECT id FROM group WHERE developername =: country]);
                        if(idOwner != null){
                            StandardCase.OwnerId = idOwner[0].id;
                        }
                    }
                }
             
            }
            else if(StandardCase.CASE_PCK_Record_Type__c == 'Payment Child Case'){
                
                StandardCase.RecordTypeId = RTPC.Id;
                
                if(StandardCase.CASE_PCK_Sourcesystem__c == 'Salesforce'){
                    String country = StandardCase.CASE_PCK_Beneficiary_country__c;
                    if(country != null && country != ''){
                        country = country + '_PaymentAnalystQueue';
                        List<group> idOwner = new List<group>([SELECT id FROM group WHERE developername =: country]);
                        if(idOwner != null){
                            StandardCase.OwnerId = idOwner[0].id;
                        }
                    }
                }
            }*/
        }
    }
    
    public static void updateOwnerAfter(List<Case> oldCaseList, List<Case> newCaseList){
        
        RecordType RTC = [Select Name, id, SobjectType from RecordType where Name = 'Case RecordType' and SobjectType  = 'Case' LIMIT 1];
		/*RecordType RTPP = [Select Name, id, SobjectType from RecordType where Name = 'Payment Parent Case' and SobjectType  = 'Case' LIMIT 1];
        RecordType RTPC = [Select Name, id, SobjectType from RecordType where Name = 'Payment Child Case' and SobjectType  = 'Case' LIMIT 1];  */      
        
        for (Case objCase: newCaseList) {
            if(objCase.RecordTypeId == RTC.Id){
                if(objCase.Status == 'In progress'){
                    if(oldCaseList[0].Status == 'CAU1'){
                        objCase.OwnerId = objCase.CASE_Resolutor__c;                  
                        system.debug('>>> despues: '+ objCase.OwnerId);
                    }
                }else if(objCase.Status == 'CAU1'){
                    if(oldCaseList[0].Status == 'In progress'){
                        if(objCase.CASE_CAU1__c != null){
                            objCase.OwnerId = objCase.CASE_CAU1__c;
                        }                       
                        system.debug('>>> pasar el caso de CAU2 a CAU1:');
                    }else if(oldCaseList[0].Status == 'CAU1'){
                        system.debug('>>> actualizar onwer en CAU1');
                        objCase.CASE_CAU1__c = objCase.OwnerId;
                        /*contact cnt = [SELECT Id FROM contact WHERE CONTACT_User__c =: objCase.OwnerId LIMIT 1];
                        if(cnt != null){
                            objCase.ContactId = cnt.Id;
                        }*/
                    }
                }
            }
            /*else if(objCase.RecordTypeId == RTPP.Id || objCase.RecordTypeId == RTPC.Id){
                if(objCase.Status == 'In progress'){
                    objCase.CASE_Analyst__c = objCase.OwnerId;
                }
                else if(objCase.Status == 'Pending of Authorization'){
                    if(objCase.RecordTypeId == RTPP.Id){
                        String country = objCase.CASE_PCK_OrderingCountry__c;
                        if(country != null && country != ''){
                            country = country + '_PaymentApprovalQueue';
                            List<group> idOwner = new List<group>([SELECT id FROM group WHERE developername =: country]);
                            if(idOwner != null){
                                objCase.OwnerId = idOwner[0].id;
                            }
                        }
                    }
                    else if(objCase.RecordTypeId == RTPC.Id){
                        String country = objCase.CASE_PCK_Beneficiary_country__c;
                        if(country != null && country != ''){
                            country = country + '_PaymentApprovalQueue';
                            List<group> idOwner = new List<group>([SELECT id FROM group WHERE developername =: country]);
                            if(idOwner != null){
                                objCase.OwnerId = idOwner[0].id;
                            }
                        }
                    }
                    
                    
                }*/
                /*else if(objCase.Status == 'Management Process'){
                 	
                    objCase.CASE_Resolutor__c = newCaseList[0].LastModifiedById;
					
                }*/
            //}
            //Activate if neccesary use random user to assign Case
            /*else{
                RecordType RTP = [Select Name, id, SobjectType from RecordType where Name = 'Payment Case' and SobjectType  = 'Case' LIMIT 1];
                if(RTP != null){
                    if(objCase.RecordTypeId == RTP.Id){
                        if(objCase.Status == 'Pending authorization'){
                            String country = objCase.CASE_PCK_Country__c;
                            String searchQueue = country+'_PaymentApprovalQueue';
                            String analystId = objCase.CASE_Analyst__c;  
                            system.debug('>>> SNJ: analystId: ' + analystId);
                            Group myGroup = [SELECT Id,Name,Type FROM Group where name=: searchQueue  and Type='Queue' LIMIT 1];
                            List<GroupMember> groupMembers = new List<GroupMember>([SELECT GroupId,Id,UserOrGroupId FROM GroupMember where GroupId =: myGroup.Id and UserOrGroupId !=: analystId]);
                            system.debug('>>> SNJ: GroupMember: ' +  groupMembers);
                            Integer randomNumber = Integer.valueof((Math.random() * groupMembers.size()));
                            system.debug('>>> SNJ: randomNumber: ' +  randomNumber);
                           	objCase.OwnerId = groupMembers.get(randomNumber).UserOrGroupId;
                            
                            
                        }
                    }
                }
              
                
            }*/
        }
    }
    
    /*public static void updateResolutor(Map<Id,Case> oldCaseMap, List<Case> newCaseList){
        
        RecordType RTPP = [Select Name, id, SobjectType from RecordType where Name = 'Payment Parent Case' and SobjectType  = 'Case' LIMIT 1];
        RecordType RTPC = [Select Name, id, SobjectType from RecordType where Name = 'Payment Child Case' and SobjectType  = 'Case' LIMIT 1];
        
        String UserID = UserInfo.getUserId();
        
        for (Case objCase: newCaseList) {
            if(objCase.RecordTypeId == RTPP.Id || objCase.RecordTypeId == RTPC.Id){
                if(oldCaseMap.get(objCase.Id).Status != objCase.Status &&  objCase.Status == 'Management Process'){
                    
                    System.debug('Last: '+ objCase.LastModifiedById);
                    objCase.CASE_Resolutor__c = UserID;
					
                }
            }
        }
    }*/
    
    /*public static void CreateChildCase(Map<Id,Case> oldCaseMap, List<Case> newCaseList){
        RecordType RTPP = [Select Name, id, SobjectType from RecordType where Name = 'Payment Parent Case' and SobjectType  = 'Case' LIMIT 1];
        RecordType RTPC = [Select Name, id, SobjectType from RecordType where Name = 'Payment Child Case' and SobjectType  = 'Case' LIMIT 1];
        
        List<Case> childCaseList = new List<Case>();
        for (Case objCase: newCaseList) {
            if(objCase.RecordTypeId == RTPP.Id){
                if(oldCaseMap.get(objCase.Id).Status != objCase.Status &&  objCase.Status == 'Management Process'){
                    if(objCase.ParentId == null){
                        Case newCase = new Case();
                            newCase.ParentId = objCase.Id;
                            newCase.Status = 'New';
                            //newCase.RecordTypeId = RTPC.Id;
                            newCase.CASE_PCK_Record_Type__c = 'Payment Child Case';
                            newCase.CASE_PCK_OrderingCountry__c = objCase.CASE_PCK_OrderingCountry__c;
                            newCase.Case_TXT_PaymentId__c = objCase.Case_TXT_PaymentId__c;
                            newCase.CASE_PCK_Beneficiary_country__c = objCase.CASE_PCK_Beneficiary_country__c;
                            newCase.CASE_PCK_Sourcesystem__c = 'Salesforce';
                        	newCase.CASE_affected_functionality__c = objCase.CASE_affected_functionality__c;
                        	newCase.Origin = objCase.Origin;
                        childCaseList.add(newCase);
                        
                    }
                }
            }            
        }
        if (!childCaseList.IsEmpty()){
            try{
                insert childCaseList;
            }
            catch(Exception e){
                system.debug('No se ha insertado el caso hijo');
            }
            
        }
    }*/
    
    public static void shareObject(List<Case> newCaseList){
        
        List<CaseShare> caseShrList = new List<CaseShare>();
        
        for (Case objCase: newCaseList) {             
            system.debug('Compartir caso');
            if(objCase.CASE_CAU1__c != null ){ //&& objCase.Status != 'New'
                caseShrList.add(HANDLER_Case.manualShare(objCase.Id,objCase.CASE_CAU1__c,'Edit'));
            }
            if(!caseShrList.isEmpty()){
                Database.SaveResult[] sr = Database.insert(caseShrList, false);
                system.debug('>>> Resultado share: ' + sr);                    
                
            }  
        }
    }
            
    public static void deleteRelatedTasks(List<Case> newCaseList){
        for (Case objCase: newCaseList) { 
            if(objCase.IsClosed || objCase.IsDeleted){
                List<Task> taskList = new List<Task>();
                taskList = [select id, whatid, Status from Task where WhatId =: objCase.Id];
                for(Task objTask : taskList){
                    objTask.Status = 'Completed';
                }
                update taskList;
            }
        }
    }
    
    public static void updateMilestoneCase(List<Case> newCaseList){
        for(Case objCase : newCaseList){
            if(objCase.IsClosed){
                system.debug('Caso Cerrado: ' + objCase.CaseNumber);
                List<CaseMilestone> cmLst = new List<CaseMilestone>();                
                cmLst = [select id, CaseId, CompletionDate from CaseMilestone where CaseId =: objCase.Id];
                for(CaseMilestone cm: cmLst){
                    if(cm.CompletionDate == null){
                        cm.CompletionDate  = system.now();
                    }
                    
                }
                update cmLst;
            }
        }
    }
    
    public static void fillBasicFields(List<Case> newCaseList){
        
        if(!newCaseList.isEmpty()){            
            //Get the only and generic Entitlement of the ORG
            List<Entitlement> entitlement = new List<Entitlement>([SELECT ID FROM Entitlement WHERE Name='SLAs']);
            
            //Get the only and generic Entitlement of the ORG
            //List<RecordType> recordTypeCase = new List<RecordType>([SELECT ID FROM RecordType WHERE Name='Internal' AND sObjectType='Case']);
            
            Profile userProfile = [SELECT Id, Name from Profile where Id =: UserInfo.getProfileId()];
            List<Contact> userContact = new List<Contact>([SELECT ID FROM Contact WHERE CONTACT_User__c=:UserInfo.getUserId()]);
            //System.debug('UserContactId: ' + userContact[0].ID);
            
            for(Case c : newCaseList){
                if(String.valueOf(c.OwnerId).startsWith('005')){
                    if(!entitlement.isEmpty()){
                        c.EntitlementId=entitlement[0].Id;
                    }
                    
                    if(c.Origin=='Internal'){
                        if(userProfile.Name == 'Intranet GTS Support Partner'){
                            if(!userContact.isEmpty()){
                                c.CASE_Submitter_General__c=userContact[0].ID;
                            }
    
                        }
                        if(userProfile.Name == 'Local Support'){
                            c.CASE_User_Submitter_General__c= UserInfo.getUserId();
                        }
                    }
                    user u = [SELECT Id, Profile.name FROM user WHERE Id =: c.OwnerId LIMIT 1];
                    if(u != null){
                        //if(u.Profile.name == 'Intranet GTS Support Partner' || u.Profile.name == 'System Administrator'){
                        if(u.Profile.name == 'Local Support' || u.Profile.name == 'Intranet GTS Support Partner'){
                            c.CASE_CAU1__c = c.OwnerId;
                        }
                    }
                }
            }
        }
    }
    
    public static void stopMilestone(List<Case> newCaseList){
        if(!newCaseList.isEmpty()){
            for(Case c: newCaseList){
                if(c.Status == 'CAU1' || c.Status == 'IT'){
                    c.IsStopped = true;
                } 
                else if(c.Status != 'CAU1' && c.Status != 'IT'){
                    c.IsStopped = false;                    
                }                 
            }
        }
    }
    
    //SNJ - 28/07/2020 - Comentar la siguiente linea antes de subir a PROD - Funcionalidad PAGO duplicado
    /*public static void closePaymentCase(List<Case> oldCaseList, List<Case> newCaseList){
        if(!newCaseList.isEmpty()){
            for(Case c: newCaseList){
                if(c.ParentId != null){
                    
                   if(c.CASE_CHK_ReverseBeneficiaryCredit__c){
                       if(c.CASE_CHK_ReverseBeneficiaryCredit__c != oldCaseList[0].CASE_CHK_ReverseBeneficiaryCredit__c){
                           c.Status = 'Refunded funds'; 
                           Case parentCase = [SELECT id, status from Case where id =: c.ParentId LIMIT 1]; 
                            if(parentCase != null){
                                parentCase.status = 'Refunded funds';
                                update parentCase;
                            }
                        }  
                    }
                    
                    if(c.Status == 'Dismissed'){
                        Case parentCase = [SELECT id, status from Case where id =: c.ParentId LIMIT 1]; 
                        if(parentCase != null){
                            parentCase.status = 'Dismissed';
                            update parentCase;
                        }
                    }
                    
                }
            }
        }
    }*/
  
    
    public static CaseShare manualShare(Id recordId, Id userOrGroupId, string caseAccessLevel){
        // Create new sharing object for the custom object Job.
        CaseShare caseShr  = new CaseShare();
   
        // Set the ID of record being shared.
        caseShr.CaseId = recordId;
        
        // Set the ID of user or group being granted access.
        caseShr.UserOrGroupId = userOrGroupId;
        
        // Set the access level.
        caseShr.CaseAccessLevel = caseAccessLevel;
        
        // Set rowCause to 'manual' for manual sharing.
        // This line can be omitted as 'manual' is the default value for sharing objects.
        caseShr.RowCause = Schema.CaseShare.RowCause.Manual;
        
        // Insert the sharing record and capture the save result. 
        // The false parameter allows for partial processing if multiple records passed 
        // into the operation.
        //Database.SaveResult sr = Database.insert(caseShr,false);
        return caseShr;
        
     
    }
   
	 public static void inProgressHours (Map<Id,Case> oldCaseMap, List<Case> newCaseList){
        BusinessHours cau2BH = [SELECT Id FROM BusinessHours WHERE name = 'CAU2 Support'];
        
        for(Case objCase: newCaseList){
            if(objCase.CASE_DATE_StartDateInProgress__c==null){
                objCase.CASE_DATE_StartDateInProgress__c = System.now();
            }
            if(oldCaseMap.get(objCase.Id).Status != objCase.Status && objCase.status == 'In progress'){
                objCase.CASE_DATE_StartDateInProgress__c = System.now();
            }
        
            if(oldCaseMap.get(objCase.Id).Status != objCase.Status &&  (objCase.Status == 'CAU1' || objCase.Status == 'IT')){
                
                Decimal hoursInProgress = BusinessHours.diff(cau2BH.Id, objCase.CASE_DATE_StartDateInProgress__c , System.now()); 
                if(objCase.CASE_NUM_DateInprogress__c != null){
                    objCase.CASE_NUM_DateInprogress__c = objCase.CASE_NUM_DateInprogress__c + (hoursInProgress / (1000*60*60));
                }else{
                    objCase.CASE_NUM_DateInprogress__c = (hoursInProgress / (1000*60*60));
                }
            }
        }
    }
    
  
    
}