zip/mdapiOTVLwr/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CASE_CHK_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CASE_CHK_ReverseBeneficiaryCredit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reverse beneficiary credit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CASE_PCK_Beneficiary_country__c</fullName>
        <label>Beneficiary country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_ISO_aplha_code_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CASE_PCK_OrderingCountry__c</fullName>
        <label>Ordering Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_ISO_aplha_code_2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CASE_PCK_Record_Type__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Case RecordType</fullName>
                </value>
                <value>
                    <fullName>Payment Parent Case</fullName>
                </value>
                <value>
                    <fullName>Payment Child Case</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Payment Case</fullName>
                    <isActive>false</isActive>
                    <label>Payment Case</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CASE_PCK_Sourcesystem__c</fullName>
        <label>Source system</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
                <value>
                    <fullName>Mulesoft</fullName>
                </value>
                <value>
                    <fullName>Stratio</fullName>
                </value>
                <value>
                    <fullName>GTS Core</fullName>
                </value>
                <value>
                    <fullName>VAM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CASE_TXT_BICCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>BIC Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CASE_TXT_PaymentId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Payment Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Country_ISO_aplha_code_2.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AE</fullName>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AN</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AQ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AS</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BF</fullName>
    </customValue>
    <customValue>
        <fullName>BG</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BI</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
    </customValue>
    <customValue>
        <fullName>BO</fullName>
    </customValue>
    <customValue>
        <fullName>BR</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <masterLabel>Country ISO aplha code 2</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CNT_CaseRefundButtons.cls
/*----------------------------------------------------------------------------------
Author:         Shahad Naji
Company:        Deloitte
Description:   	Controller class por CMP_CaseRefundButtons
				Book To Book Payment Refund process manually triggered from the GTS back-end portal by an agent of the Santander ordering bank, triggering in parallel the refund to the ordering account & the reimbursement petition to the beneficiary bank for confirmation
Test Class:     TBD
History
<Date>			<Author>		<Description>
14/08/2020		Shahad Naji     Initial version
----------------------------------------------------------------------------------*/
public class CNT_CaseRefundButtons {

    
        /*----------------------------------------------------------------------------------
Author:         Shahad Naji 
Company:        Deloitte
Description:    Method to return case data
History
<Date>          <Author>             <Description>
14/08/2020      Shahad Naji        Initial version
----------------------------------------------------------------------------------*/ 
    
    @AuraEnabled 
    public static ReturnValue getCaseData(String caseId){
        ReturnValue rv = null;
        Map<String, Object> value = new Map<String, Object>();
        Case iCase = null;
        try{
            iCase = [SELECT Id, Status, CASE_PCK_Sourcesystem__c, CASE_CHK_Reverse_ordering_debit__c, CASE_CHK_Reverse_limits_update__c, CASE_CHK_Reverse_FX__c, CASE_CHK_ReverseBeneficiaryCredit__c, CASE_PCK_Record_Type__c, CASE_TXT_PaymentId__c, CASE_PCK_OrderingCountry__c, CASE_TXT_BICCode__c, CASE_PCK_Beneficiary_country__c, CASE_CHK_Approved__c
                 FROM Case WHERE Id =: caseId LIMIT 1];
            value.put('output', iCase);
            rv = new ReturnValue(true,value);
        }catch(Exception e){            
            System.debug('CNT_CaseRefundButtons.getCaseData: ' + e.getMessage() + ', in line: ' + e.getLineNumber());            
            rv = new ReturnValue(false, null, e.getMessage());
        }
        return rv;
    }
 
    
    /*----------------------------------------------------------------------------------
Author:         Shahad Naji 
Company:        Deloitte
Description:    Method to Reverse Ordering debit
History
<Date>          <Author>             <Description>
14/08/2020      Shahad Naji        Initial version
----------------------------------------------------------------------------------*/ 
	@AuraEnabled
    public static ReturnValue reverseOrderingDebit(String caseId, String book_to_book_id){
        ReturnValue rv = null;
        Map<String, Object> value = new Map<String, Object>();
        Case iCase = null;
        try {
            //PARCHE_FLOWERPOWER_SNJ
            //WS_CancelBookToBook cancelBookToBook = new WS_CancelBookToBook(book_to_book_id);
            //String result = cancelBookToBook.execute('S','E');
            String result = 'OK';
            if(result != null){
                if(result == 'OK'){
                    system.debug('>>> SNJ OK WS_CancelBookToBook');
                    value.put('output', 'OK');
                    rv = new ReturnValue(true,value); 
                    iCase = [SELECT id, Status, CASE_CHK_Reverse_ordering_debit__c  FROM Case WHERE Id =: caseId LIMIT 1]; 
                    iCase.CASE_CHK_Reverse_ordering_debit__c = true;
                    iCase.Status = 'Management Process';
                    update iCase;
                }else{
                    value.put('output', 'KO');
                    rv = new ReturnValue(false,value);
                    system.debug('>>> SNJ KO 1 WS_CancelBookToBook');
                }
            }else{
                value.put('output', 'KO');
                rv = new ReturnValue(false,value);
               system.debug('>>> SNJ KO 2 WS_CancelBookToBook');
            }
            
            
        }catch (Exception e) {
            System.debug('CNT_CaseRefundButtons.reverseOrderingDebit: ' + e.getMessage() + ', in line: ' + e.getLineNumber());
            rv = new ReturnValue(false, null, e.getMessage());
        }
        return rv;
    }
    
    
    
       /*----------------------------------------------------------------------------------
Author:         Shahad Naji 
Company:        Deloitte
Description:    Method to Reverse beneficiary credit
History
<Date>          <Author>             <Description>
14/08/2020      Shahad Naji        Initial version
----------------------------------------------------------------------------------*/ 
	@AuraEnabled
    public static ReturnValue reverseBeneficiaryCredit(String caseId, String operation_id){
        ReturnValue rv = null;
        Map<String, Object> value = new Map<String, Object>();
        Case iCase = null;
        try {
            //PARCHE_FLOWERPOWER_SNJ
            //WS_CancelPaymentOrchestrator cancelPaymentOrch = new WS_CancelPaymentOrchestrator(operation_id);
            //String result = cancelPaymentOrch.execute('D','E');
            String result = 'OK';
            if(result != null){
                if(result == 'OK'){
                    system.debug('>>> SNJ OK WS_CancelPaymentOrchestrator');
                    value.put('output', 'OK');
                    rv = new ReturnValue(true,value); 
                    iCase = [SELECT id, Status, CASE_CHK_ReverseBeneficiaryCredit__c  FROM Case WHERE Id =: caseId LIMIT 1]; 
                    iCase.CASE_CHK_ReverseBeneficiaryCredit__c = true;
                    iCase.Status = 'Management Process';
                    update iCase;
                  
                }else{
                    value.put('output', 'KO');
                    rv = new ReturnValue(false,value);
                    system.debug('>>> SNJ KO 1 WS_CancelPaymentOrchestrator');
                }
            }else{
                value.put('output', 'KO');
                rv = new ReturnValue(false,value);
               system.debug('>>> SNJ KO 2 WS_CancelPaymentOrchestrator');
            }
            
            
        }catch (Exception e) {
            System.debug('CNT_CaseRefundButtons.reverseBeneficiaryCredit: ' + e.getMessage() + ', in line: ' + e.getLineNumber());
            rv = new ReturnValue(false, null, e.getMessage());
        }
        return rv;
    }
    
       /*----------------------------------------------------------------------------------
Author:         Shahad Naji 
Company:        Deloitte
Description:    Method to Reverse FX 
History
<Date>          <Author>             <Description>
14/08/2020      Shahad Naji        Initial version
----------------------------------------------------------------------------------*/ 
    @AuraEnabled
    public static ReturnValue reverseFX(String caseId, WRAPPER_PaymentDetail.OperationDetail paymentData){
        ReturnValue rv = null;
        Map<String, Object> value = new Map<String, Object>();
        Case iCase = new Case();
        Case iParentCase = new Case();
        try {
            //PARCHE_FLOWERPOWER_SNJ
           //  WS_CancelBuySell cancelBuySell = new WS_CancelBuySell();
           // String result = cancelBuySell.execute(paymentData);
            String result = 'OK';
            if(result != null){
                if(result == 'OK'){                    
                    value.put('output', 'OK');
                    rv = new ReturnValue(true,value); 
                    iCase = [SELECT id, Status, CASE_CHK_ReverseBeneficiaryCredit__c, ParentId  FROM Case WHERE Id =: caseId LIMIT 1]; 
                   /* if(iCase.ParentId != ''){
                        system.debug('SNJ parent: ' + iCase.ParentId);
                        iParentCase =  [SELECT id, Status, CASE_CHK_Reverse_FX__c FROM Case WHERE Id =: caseId LIMIT 1];
                        if(iParentCase.Status == 'Management Process' && iParentCase.CASE_CHK_Reverse_FX__c == false){
                            iParentCase.CASE_CHK_Reverse_FX__c = true;
                            update iParentCase;
                        }
                    }else{
                        system.debug('SNJ parent: NO PARENT');
                    }*/
                    
                }else{
                    value.put('output', 'KO');
                    rv = new ReturnValue(false,value);
                    system.debug('>>> SNJ KO 1 WS_CancelBuySell');
                }
            }else{
                value.put('output', 'KO');
                rv = new ReturnValue(false,value);
                system.debug('>>> SNJ KO 2 WS_CancelBuySell');
            }
            
            
        }catch (Exception e) {
            System.debug('CNT_CaseRefundButtons.reverseBeneficiaryCredit: ' + e.getMessage() + ', in line: ' + e.getLineNumber());
            rv = new ReturnValue(false, null, e.getMessage());
        }
        return rv;
    }
    
        /*----------------------------------------------------------------------------------
    Author:         Shahad Naji
    Company:        Deloitte
    Description:    Gets the detail of a payment
    History
    <Date>			<Author>		       <Description>
    16/09/2020      Shahad Naji       		Initial version - besed on CNT_PaymentsPaymentDetail
    ----------------------------------------------------------------------------------*/
    @AuraEnabled
    public static ReturnValue getPaymentDetail(String paymentId){        
        ReturnValue response = null;
        response = CNT_PAY_PaymentOptions.getPaymentDetail(paymentId);
        return response;
    }
}