zip/mdapiOTVLwr/unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>USER_CHK_CashNexus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cash Nexus User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>USER_NumberFormat__c</fullName>
        <description>Number format of the user</description>
        <inlineHelpText>Enter a number format for the user.</inlineHelpText>
        <label>Number format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>###.###.###,##</fullName>
                    <default>true</default>
                    <label>###.###.###,##</label>
                </value>
                <value>
                    <fullName>###,###,###.##</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>USER_TXT_BIC__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>BIC</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USER_TXT_GlobalId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Global Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USER_TXT_LocalUid__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Local UID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>USER_TXT_Signer_email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Signer email</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>USER_country__c</fullName>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Name</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_DateFormat__c</fullName>
        <description>Date format for the user</description>
        <inlineHelpText>Enter a date format.</inlineHelpText>
        <label>Date format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>dd/MM/yyyy</fullName>
                    <default>true</default>
                    <label>dd/MM/yyyy</label>
                </value>
                <value>
                    <fullName>MM/dd/yyyy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/CNT_UserData.cls
public without sharing class CNT_UserData {
    
    public static User getUserData(String userId)
    {
        User result = new User();
        if(userId==''){ 
            userId=UserInfo.getUserId();
        }
        List<User> user = [SELECT Id, FirstName, LastName, Alias, Profile.Name, UserRole.Name, Email, MobilePhone, USER_TXT_Signer_email__c,USER_TXT_LocalUid__c, LanguageLocaleKey, User_DateFormat__c, USER_NumberFormat__c, USER_CHK_CashNexus__c, USER_TXT_GlobalId__c, USER_country__c, USER_TXT_BIC__c, UserRoleId FROM User WHERE Id = :userId LIMIT 1 ];
        if(user.size() > 0) {
            result = user.get(0);
        }
        
        return result;
    }
    
    public static List<User> getUsersDataGlobal(List<String> userIds)
    {
        List<User> result = new List<User>();
        
        if(userIds.size() > 0){     
            List<User> users = [SELECT Id, Name, FirstName, LastName, Alias, Profile.Name, UserRole.Name, Email, MobilePhone, USER_TXT_Signer_email__c,USER_TXT_LocalUid__c, LanguageLocaleKey, User_DateFormat__c, USER_NumberFormat__c, USER_CHK_CashNexus__c, USER_TXT_GlobalId__c, USER_country__c, USER_TXT_BIC__c, UserRoleId FROM User WHERE USER_TXT_GlobalId__c IN :userIds];
            if(users.size() > 0) {
                result = users;
            }
        }
        
        return result;
    }


}