zip/mdapiOTVLwr/unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>USER_LUP_parentBackOfficeUser__c</fullName>
        <description>This lookup is used for the Login As functionality. It allows a back office user to have one, and only one, dummy user associated with it, to be able to login as a portal user.</description>
        <label>Parent Back Office User</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 3)</booleanFilter>
            <filterItems>
                <field>$Source.isDummyBackOfficeUser__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Support</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <relationshipName>USER_associatedDummyUser</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>isDummyBackOfficeUser__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate whether the user is a back office dummy user, it will take part in the Login As functionality for Back Office users.</description>
        <label>Dummy Back Office User</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/HANDLER_User_Test.cls
/*----------------------------------------------------------------------------------
Author:         Guillermo Giral
Company:        Deloitte
Description:    Test class for the User handler class
History
<Date>          <Author>        	<Description>
24/06/2020      Guillermo Giral     Initial version
----------------------------------------------------------------------------------*/
@isTest
public class HANDLER_User_Test {
    @testSetup
    static void setup(){
        User currentUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        User supportUserCopy;
        
        System.runAs(currentUser){
            // Get the support profile
            Profile p = [SELECT Id FROM Profile WHERE Name='Support']; 
            UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        
        	// Create a support user
        	User supportUser = new User(Alias = 'scau', Email='supportUser@testorg.com', 
                                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id, UserRoleId = portalRole.Id,
                                TimeZoneSidKey='America/Los_Angeles', UserName='standarduserGTS@acmesupport.com', isActive = true);
        	insert supportUser;
            supportUserCopy = supportUser;
        }
        
        // Create a dummy user associated with a community profile (Nexus User)
       	Account acc = new Account(
            			Name = 'Test Account',
            			OwnerId = supportUserCopy.Id
        );
        insert acc;
        Contact c = new Contact(
        		FirstName = 'Test',
        		LastName = 'Portal',
        		AccountId = acc.Id,
        		Email = 'testPortal@testSF.com');
        insert c;  
        
        System.runAs(currentUser){
            Profile portalProfile = [SELECT Id FROM Profile WHERE Name = 'Nexus User'];
            User dummyUser = new User(Alias = 'scau', Email='supportUser@testorg.com', 
                                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = portalProfile.Id, 
                                TimeZoneSidKey='America/Los_Angeles', UserName='standarduserGTS@acme.com',
                                ContactId = c.Id, isActive = false, USER_LUP_parentBackOfficeUser__c = supportUserCopy.Id,
                                isDummyBackOfficeUser__c = true);
            insert dummyUser;
        }
    }
    
	@isTest
    public static void enforceOnlyOneParentDummyUser_Test(){
        // Get the parent support user
        User parentSupportUser = [SELECT Id, Username FROM User WHERE Username = 'standarduserGTS@acmesupport.com'];
        Account businessAccount = [SELECT Id FROM Account WHERE Name = 'Test Account'];
        Contact c = new Contact(
        		FirstName = 'Test',
        		LastName = 'Portal 2',
        		AccountId = businessAccount.Id,
        		Email = 'testPortal@testSF.com');
        insert c;  
        // Create a dummy user and try to assign it a support user with a children dummy
        Profile portalProfile = [SELECT Id FROM Profile WHERE Name = 'Nexus User'];
        User currentUser = [SELECT Id from User where Id = :UserInfo.getUserId() ];
        System.runAs(currentUser){
          User dummyUser = new User(Alias = 'scau', Email='supportUser@testorg.com', 
                                  EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                  LocaleSidKey='en_US', ProfileId = portalProfile.Id, 
                                  TimeZoneSidKey='America/Los_Angeles', UserName='standarduserGTSDummy2@acme.com',
                                  ContactId = c.Id, isActive = false, USER_LUP_parentBackOfficeUser__c = parentSupportUser.Id,
                                  isDummyBackOfficeUser__c = true);
        
            // Run the test, in this case an error shold be thrown and caught
            Test.startTest();
            try{
                insert dummyUser;
            } catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains(parentSupportUser.Username) ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);    
            } 
            
            // If the user is created and then updated to match the same parent, an error should be thrown again
            try{
                dummyUser.USER_LUP_parentBackOfficeUser__c = null;
                insert dummyUser;
                dummyUser.USER_LUP_parentBackOfficeUser__c = parentSupportUser.Id;
                update dummyUser;
            } catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains(parentSupportUser.Username) ? true : false;
                System.AssertEquals(expectedExceptionThrown, true);
            }
            Test.stopTest();  
        }    
    }
}