force-app/main/default/objects/OTPValidation__e/OTPValidation__e.object-meta.xml
<CustomObject>
    <label>OTPValidation</label>
    <pluralLabel>OTPValidation</pluralLabel>
</CustomObject>

force-app/main/default/objects/OTPValidation__e/fields/scaUid__c.field-meta.xml
<CustomField>
    <fullName>scaUid__c</fullName>
    <label>scaUid</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OTPValidation__e/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

zip/mdapiOTVLwr/unpackaged/objects/OTPValidationOTV__e.object
<CustomObject>
    <fields>
        <fullName>scaUid__c</fullName>
        <label>scaUid</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>OTPValidationOTV</label>
    <pluralLabel>OTPValidationOTV</pluralLabel>
</CustomObject>

force-app/main/default/classes/WS_OTPValidationService.cls
@RestResource(urlMapping='/OTPValidationService/*')
global with sharing class WS_OTPValidationService {
    

    @HttpPost
    global static string validateOTP(String jti, String iat, String status, String scaUid, String configurationUid) {
        system.debug('Entra');
        try{
		 	string returnMessage;
            //Publish the platform event  
            system.debug('configUid');
            system.debug(configurationUid);
            if(configurationUid == '4a5be88c-7123-466a-a99d-99da232f27a6'){
                //configUid para proceso de activación One Trade View
                OTPValidationOTV__e validationEvent = new OTPValidationOTV__e(status__c = status, scaUid__c = scaUid);
            	System.debug(validationEvent);
            	// Call method to publish events
            	Database.SaveResult sr = EventBus.publish(validationEvent);
                // Inspect publishing result for each event
                if (sr.isSuccess()) {
                    System.debug('Successfully published event. OTV CERT');
                    returnMessage='Successfully published event. OTV CERT';
                } else {
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('Error returned: ' +
                                     err.getStatusCode() +
                                     ' - ' +
                                     err.getMessage());
                        returnMessage='The following exception has occurred: ' + err.getMessage();
                    }
                }
            }else{
                //configUid para pagos
                OTPValidation__e validationEvent = new OTPValidation__e(status__c = status, scaUid__c = scaUid);
            	System.debug(validationEvent);
            	// Call method to publish events
            	Database.SaveResult sr = EventBus.publish(validationEvent);
                // Inspect publishing result for each event
                if (sr.isSuccess()) {
                    System.debug('Successfully published event.');
                    returnMessage='Successfully published event.';
                } else {
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('Error returned: ' +
                                     err.getStatusCode() +
                                     ' - ' +
                                     err.getMessage());
                        returnMessage='The following exception has occurred: ' + err.getMessage();
                    }
                }
            }
            return returnMessage;
        } catch (Exception e) {
            System.debug('OTPValidationService: ' + e.getMessage() + ', in line: ' + e.getLineNumber());
            throw new CalloutException('The following exception has occurred: ' + e.getMessage()+', in line: ' + e.getLineNumber()); 
        }
    }
}