force-app/main/default/objects/ContactUsPhoneMail__c/ContactUsPhoneMail__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to set the values of the phone contact and email used in the community page contact us.</description>
    <label>ContactUsPhoneMail</label>
</CustomObject>

force-app/main/default/objects/ContactUsPhoneMail__c/fields/contactUsMail__c.field-meta.xml
<CustomField>
    <fullName>contactUsMail__c</fullName>
    <description>Mail for the contact us to the community page contac us.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>contactUsMail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactUsPhoneMail__c/fields/phoneNumberContacUs__c.field-meta.xml
<CustomField>
    <fullName>phoneNumberContacUs__c</fullName>
    <description>Phone number for the contact us to the community page contac us.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>phoneNumberContacUs</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CNT_ContactUsController_Test.cls
/*----------------------------------------------------------------------------------
Author:         Pablo Tejedor 
Company:        Deloitte
Description:    Class to test CNT_ContactUsController
Test Class:     CNT_ContactUsController_Test
History
<Date>			<Author>		<Description>
17/02/2020		Pablo Tejedor    Initial version
----------------------------------------------------------------------------------*/

@isTest
public with sharing class CNT_ContactUsController_Test {
    
    @isTest
    static void getDataContacUstest(){
        
        ContactUsPhoneMail__c csTest = new ContactUsPhoneMail__c();
		csTest.Name = 'ContactUsParams';
        csTest.contactUsMail__C = 'OneTradeClientService1@gruposantander.com';
		csTest.phoneNumberContacUs__c = '113123123';
		insert csTest;
        
        Test.startTest();
        ContactUsPhoneMail__c vuelta = CNT_ContactUsController.getDataContacUs();
        Test.stopTest();
        
        system.assertNotEquals(null, vuelta, 'la custom seting no esta vacia');
        

        
    }

}