force-app/main/default/objects/Comercial_Code__mdt/Comercial_Code__mdt.object-meta.xml
<CustomObject>
    <label>Comercial Code</label>
    <pluralLabel>Comercial code</pluralLabel>
</CustomObject>

force-app/main/default/objects/Comercial_Code__mdt/fields/PAY_PCK_CommercialCode__c.field-meta.xml
<CustomField>
    <fullName>PAY_PCK_CommercialCode__c</fullName>
    <label>Commercial code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20000</fullName>
                <default>true</default>
                <label>20000</label>
            </value>
            <value>
                <fullName>20002</fullName>
            </value>
            <value>
                <fullName>20005</fullName>
            </value>
            <value>
                <fullName>20007</fullName>
            </value>
            <value>
                <fullName>20008</fullName>
            </value>
            <value>
                <fullName>20024</fullName>
            </value>
            <value>
                <fullName>20028</fullName>
            </value>
            <value>
                <fullName>20040</fullName>
            </value>
            <value>
                <fullName>20070</fullName>
            </value>
            <value>
                <fullName>20075</fullName>
            </value>
            <value>
                <fullName>20080</fullName>
            </value>
            <value>
                <fullName>20090</fullName>
            </value>
            <value>
                <fullName>20500</fullName>
            </value>
            <value>
                <fullName>20700</fullName>
            </value>
            <value>
                <fullName>20750</fullName>
            </value>
            <value>
                <fullName>20830</fullName>
            </value>
            <value>
                <fullName>10080</fullName>
            </value>
            <value>
                <fullName>10096</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Comercial_Code__mdt/fields/PAY_PCK_CommercialCodeText__c.field-meta.xml
<CustomField>
    <fullName>PAY_PCK_CommercialCodeText__c</fullName>
    <label>Commercial code text</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Communication, Construction and Transportation Services</fullName>
                <default>true</default>
                <label>20000 - Communication, Construction and Transportation Services</label>
            </value>
            <value>
                <fullName>IT Services</fullName>
                <label>20002 - IT Services</label>
            </value>
            <value>
                <fullName>Business, Professional, Fee-Based and Sundry Technical Services</fullName>
                <label>20005 - Business, Professional, Fee-Based and Sundry Technical Services</label>
            </value>
            <value>
                <fullName>Personal, Cultural and Recreational Services</fullName>
                <label>20007 - Personal, Cultural and Recreational Services</label>
            </value>
            <value>
                <fullName>Information Services</fullName>
                <label>20008 - Information Services</label>
            </value>
            <value>
                <fullName>Pensions, Dependent´s Pensions, Family Aids and Other Donations</fullName>
                <label>20024 - Pensions, Dependent´s Pensions, Family Aids and Other Donations</label>
            </value>
            <value>
                <fullName>Diplomatic Delegations, Missions, International Organizations and other Delegations abroad</fullName>
                <label>20028 - Diplomatic Delegations, Missions, International Organizations and other Delegations abroad</label>
            </value>
            <value>
                <fullName>Transportation Equipment and Machinery Rental</fullName>
                <label>20040 - Transportation Equipment and Machinery Rental</label>
            </value>
            <value>
                <fullName>Exits for Tourism</fullName>
                <label>20070 - Exits for Tourism</label>
            </value>
            <value>
                <fullName>Exits for Deposits in foreign currency established in Chile</fullName>
                <label>20075 - Exits for Deposits in foreign currency established in Chile</label>
            </value>
            <value>
                <fullName>Exits not contemplated in other International Exchange Operation Codes</fullName>
                <label>20080 - Exits not contemplated in other International Exchange Operation Codes</label>
            </value>
            <value>
                <fullName>Exits for future Transfers or for direct payments abroad</fullName>
                <label>20090 - Exits for future Transfers or for direct payments abroad</label>
            </value>
            <value>
                <fullName>Import hedges</fullName>
                <label>20500 - Import hedges</label>
            </value>
            <value>
                <fullName>Insurance and Reinsurance Premiums,  and other related Exits</fullName>
                <label>20700 - Insurance and Reinsurance Premiums,  and other related Exits</label>
            </value>
            <value>
                <fullName>Compensations for/without Insurance Contracts</fullName>
                <label>20750 - Compensations for/without Insurance Contracts</label>
            </value>
            <value>
                <fullName>Contributions, Borrowings and Donations to Corporation and other legal non-profit entities (Law Decree N° 1.183 of 1975)</fullName>
                <label>20830 - Contributions, Borrowings and Donations to Corporation and other legal non-profit entities (Law Decree N° 1.183 of 1975)</label>
            </value>
            <value>
                <fullName>Entries  not contemplated in other Exchange Operation Codes</fullName>
                <label>10080 - Entries  not contemplated in other Exchange Operation Codes</label>
            </value>
            <value>
                <fullName>Entries from M.C.F. Entities on remittances or deposits of notes in foreign currency</fullName>
                <label>10096 - Entries from M.C.F. Entities on remittances or deposits of notes in foreign currency</label>
            </value>
            <value>
                <fullName>10080 - Ingresos no contempladas en otros Códigos de Operaciones de Cambios</fullName>
                <isActive>false</isActive>
                <label>10080 - Ingresos no contempladas en otros Códigos de Operaciones de Cambios</label>
            </value>
            <value>
                <fullName>10096 - Ingresos de Entidades del M.C.F. por remesas o depósitos de documentos en moneda extranjera</fullName>
                <isActive>false</isActive>
                <label>10096 - Ingresos de Entidades del M.C.F. por remesas o depósitos de documentos en moneda extranjera</label>
            </value>
            <value>
                <fullName>20000 - Servicios de Comunicación, Construcción y Transporte</fullName>
                <isActive>false</isActive>
                <label>20000 - Servicios de Comunicación, Construcción y Transporte</label>
            </value>
            <value>
                <fullName>20002 - Servicios de Informática</fullName>
                <isActive>false</isActive>
                <label>20002 - Servicios de Informática</label>
            </value>
            <value>
                <fullName>20005 - Servicios Empresariales, Profesionales, Honorarios y Técnicos varios</fullName>
                <isActive>false</isActive>
                <label>20005 - Servicios Empresariales, Profesionales, Honorarios y Técnicos varios</label>
            </value>
            <value>
                <fullName>20007 - Servicios Personales, Culturales y Recreativos</fullName>
                <isActive>false</isActive>
                <label>20007 - Servicios Personales, Culturales y Recreativos</label>
            </value>
            <value>
                <fullName>20008 - Servicios de Información</fullName>
                <isActive>false</isActive>
                <label>20008 - Servicios de Información</label>
            </value>
            <value>
                <fullName>20024 - Jubilaciones, Montepíos, Ayudas Familiares, Herencias y Otras Donaciones</fullName>
                <isActive>false</isActive>
                <label>20024 - Jubilaciones, Montepíos, Ayudas Familiares, Herencias y Otras Donaciones</label>
            </value>
            <value>
                <fullName>20028 - Representaciones Diplomáticas, Misiones y otras Oficinas de Representación en el exterior</fullName>
                <isActive>false</isActive>
                <label>20028 - Representaciones Diplomáticas, Misiones y otras Oficinas de Representación en el exterior</label>
            </value>
            <value>
                <fullName>20040 - Arrendamiento de Equipo de Transporte y Maquinaria</fullName>
                <isActive>false</isActive>
                <label>20040 - Arrendamiento de Equipo de Transporte y Maquinaria</label>
            </value>
            <value>
                <fullName>20070 - Egresos por Turismo</fullName>
                <isActive>false</isActive>
                <label>20070 - Egresos por Turismo</label>
            </value>
            <value>
                <fullName>20075 - Egresos por Depósitos en moneda extranjera constituidos en Chile</fullName>
                <isActive>false</isActive>
                <label>20075 - Egresos por Depósitos en moneda extranjera constituidos en Chile</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Status__mdt/Payment_Status__mdt.object-meta.xml
<CustomObject>
    <label>Payment_Status</label>
    <pluralLabel>Payment_Statuses</pluralLabel>
</CustomObject>

force-app/main/default/objects/Payment_Status__mdt/fields/PAY_PCK_Status__c.field-meta.xml
<CustomField>
    <fullName>PAY_PCK_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Authorized</fullName>
                <default>true</default>
                <label>Authorized</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Not authorized</fullName>
            </value>
            <value>
                <fullName>On hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending of authorization</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Status__mdt/fields/PAY_TXT_StatusCode__c.field-meta.xml
<CustomField>
    <fullName>PAY_TXT_StatusCode__c</fullName>
    <label>Status code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CNT_B2B_ComercialCode.cls
public class CNT_B2B_ComercialCode {

    
    @AuraEnabled(cacheable=true)
    public static ReturnValue getCommercialCodes(){
        ReturnValue response = null;
        try {
            Map<String, Object> value = new Map<String, Object>();          
            List<WRAPPER_PaymentList.WRAPPER_CommercialCode> commercialCodeList = new List<WRAPPER_PaymentList.WRAPPER_CommercialCode>();
            List<Comercial_Code__mdt> commercialCode_mdt = new List<Comercial_Code__mdt>([SELECT PAY_PCK_CommercialCode__c, toLabel(PAY_PCK_CommercialCodeText__c) FROM Comercial_Code__mdt]); 
            for(Comercial_Code__mdt cc : commercialCode_mdt){
                WRAPPER_PaymentList.WRAPPER_CommercialCode item = new WRAPPER_PaymentList.WRAPPER_CommercialCode();
                item.commercialCode = cc.PAY_PCK_CommercialCode__c;
                item.parsedCommercialCode = cc.PAY_PCK_CommercialCodeText__c;
                commercialCodeList.add(item);
            }
            value.put('commercialCodeList', commercialCodeList);      
            response = new ReturnValue(true, value);
        } catch (Exception e) {
            System.debug('CNT_B2B_ComercialCode.getCommercialCodes: ' + e.getMessage() + ', in line: ' + e.getLineNumber());
            response = new ReturnValue(false, null, e.getMessage());
        }
        return response;
    }




    /* public static List<WRAPPER_PaymentList.WRAPPER_Status> getStatusList(){
        List<WRAPPER_PaymentList.WRAPPER_Status> statusList = new List<WRAPPER_PaymentList.WRAPPER_Status>();  
        try{
            List<Payment_Status__mdt> statusList_mtd = new List<Payment_Status__mdt>([SELECT PAY_TXT_StatusCode__c, toLabel(PAY_PCK_Status__c) FROM Payment_Status__mdt]); 
            for(Payment_Status__mdt s : statusList_mtd){
                WRAPPER_PaymentList.WRAPPER_Status item = new WRAPPER_PaymentList.WRAPPER_Status();
                item.statusName = s.PAY_TXT_StatusCode__c;
                item.parsedStatusName = s.PAY_PCK_Status__c;
                statusList.add(item);
            }
        }catch(Exception e){
            System.debug('CNT_Payments.getStatusList: ' + e.getMessage() + ', in line: ' + e.getLineNumber());
            return statusList;
        }
        return statusList;
    }
    */
}