force-app/main/default/objects/Login_Error__mdt/Login_Error__mdt.object-meta.xml
<CustomObject>
    <label>Login Error</label>
    <pluralLabel>Login Errors</pluralLabel>
</CustomObject>

force-app/main/default/objects/Login_Error__mdt/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <label>Error Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Login_Error__mdt/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Login_Error__mdt/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EN</fullName>
                <default>true</default>
                <label>EN</label>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>PT</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>PL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CNT_LoginError.cls
/*----------------------------------------------------------------------------------
Author:         Antonio Duarte
Company:        Deloitte
Description:    Controller of CMP_LoginError 
Test Class:     CNT_LoginError_Test
History
<Date>          <Author>        	<Description>
19/08/2020      Antonio Duarte     	Initial version
----------------------------------------------------------------------------------*/
public class CNT_LoginError {
	
    @AuraEnabled
    public static String getErrorMessage(String errorCode, String language){
        String errorMessage = '';
        
        try{
            if(errorCode == null || ''.equals(errorCode) || 'Not found'.equals(errorCode)){
                errorCode = 'Default';
            }
            if(language == null || ''.equals(language)){
                language = 'EN';
            }
            
            List<Login_Error__mdt> loginErrors = [SELECT Error_Message__c, Language__c, Error_Code__c FROM Login_Error__mdt];
            
            for(Login_Error__mdt error : loginErrors){
                if(error.Error_Code__c.equals(errorCode) && error.Language__c.equals(language)){
                    errorMessage = error.Error_Message__c;
                    break;
                }else if(error.Error_Code__c.equals('Default') && error.Language__c.equals(language)){
                    errorMessage = error.Error_Message__c;
                }
            }
            
        }catch(Exception e){
            errorMessage = 'Undefined Error';
        }
        
        return errorMessage;
    }
}