force-app/main/default/objects/Payment_Status__mdt/Payment_Status__mdt.object-meta.xml
<CustomObject>
    <label>Payment_Status</label>
    <pluralLabel>Payment_Statuses</pluralLabel>
</CustomObject>

force-app/main/default/objects/Payment_Status__mdt/fields/PAY_PCK_Reason__c.field-meta.xml
<CustomField>
    <fullName>PAY_PCK_Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending of my authorization</fullName>
                <default>true</default>
                <label>Pending of my authorization</label>
            </value>
            <value>
                <fullName>Pending authorization by others</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Scheduled next 7 days</fullName>
            </value>
            <value>
                <fullName>Completed last 7 days</fullName>
            </value>
            <value>
                <fullName>Rejected last 7 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Status__mdt/fields/PAY_PCK_Status__c.field-meta.xml
<CustomField>
    <fullName>PAY_PCK_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Authorized</fullName>
                <default>true</default>
                <label>Authorized</label>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>In review</fullName>
            </value>
            <value>
                <fullName>Not authorized</fullName>
            </value>
            <value>
                <fullName>On hold</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending of authorization</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Payments_Utilities.cls
/*----------------------------------------------------------------------------------
Author:         Shahad Naji
Company:        Deloitte
Description:    Holds auxiliar functions
Test Class:     Payments_Utilities_Test
History
<Date>			<Author>		<Description>
03/06/2020		Shahad Naji     Initial version
----------------------------------------------------------------------------------*/
public without sharing class Payments_Utilities {
    
    /*----------------------------------------------------------------------------------
    Author:         Shahad Naji
    Company:        Deloitte
    Description:    Returns Payment_Status__mdt
    History
    <Date>			<Author>		<Description>
    03/06/2020		Shahad Naji     Initial version
    ----------------------------------------------------------------------------------*/    
    public static Payment_Status__mdt getPaymentStatusRowByStatus(String input){
        Payment_Status__mdt output = new Payment_Status__mdt();
        try{
            output = [SELECT toLabel(PAY_PCK_Status__c), toLabel(PAY_PCK_Reason__c) FROM Payment_Status__mdt WHERE Label =: input LIMIT 1];
        }catch(Exception e){            
            System.debug('Exception type caught: ' + e.getTypeName());    
            System.debug('Message: ' + e.getMessage());
            System.debug('Cause: ' + e.getCause());    // returns null
            System.debug('Line number: ' + e.getLineNumber());    
            System.debug('Stack trace: ' + e.getStackTraceString());  
        }        
        return output;
    }
    /*----------------------------------------------------------------------------------
    Author:         Shahad Naji
    Company:        Deloitte
    Description:    Returns Payment_Status__mdt
    History
    <Date>			<Author>		<Description>
    03/06/2020		Shahad Naji     Initial version
    ----------------------------------------------------------------------------------*/    
    public static List<Payment_Status__mdt> getPaymentStatusRowByReason(String input){
        List<Payment_Status__mdt> output = new List<Payment_Status__mdt>();
        try{
            output = [SELECT toLabel(PAY_PCK_Status__c), toLabel(PAY_PCK_Reason__c) FROM Payment_Status__mdt WHERE PAY_PCK_Reason__c =: input LIMIT 1];
        }catch(Exception e){            
            System.debug('Exception type caught: ' + e.getTypeName());    
            System.debug('Message: ' + e.getMessage());
            System.debug('Cause: ' + e.getCause());    // returns null
            System.debug('Line number: ' + e.getLineNumber());    
            System.debug('Stack trace: ' + e.getStackTraceString());  
        }        
        return output;
    }
    
}