force-app/main/default/objects/Purpose_of_Payment__mdt/Purpose_of_Payment__mdt.object-meta.xml
<CustomObject>
    <description>Created for the picklist values in the purpose of payment field of Book to Book payments.</description>
    <label>Purpose of Payment</label>
    <pluralLabel>Purposes of Payment</pluralLabel>
</CustomObject>

force-app/main/default/objects/Purpose_of_Payment__mdt/fields/PUR_PCK_Purpose__c.field-meta.xml
<CustomField>
    <fullName>PUR_PCK_Purpose__c</fullName>
    <label>Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Charitable Aid</fullName>
                <default>true</default>
                <label>Charitable Aid</label>
            </value>
            <value>
                <fullName>Payment for identifiable goods</fullName>
            </value>
            <value>
                <fullName>Direct Capital investment in an Enterprise</fullName>
            </value>
            <value>
                <fullName>Payment for identifiable services</fullName>
            </value>
            <value>
                <fullName>Repatriation of sale of identifiable goods</fullName>
            </value>
            <value>
                <fullName>Repatriation of sale of identifiable services</fullName>
            </value>
            <value>
                <fullName>Property purchase</fullName>
            </value>
            <value>
                <fullName>Mortgage repayment</fullName>
            </value>
            <value>
                <fullName>Property rental/maintenance</fullName>
            </value>
            <value>
                <fullName>Salary/payroll</fullName>
            </value>
            <value>
                <fullName>Travel costs</fullName>
            </value>
            <value>
                <fullName>Living costs</fullName>
            </value>
            <value>
                <fullName>Repayment of a loan</fullName>
            </value>
            <value>
                <fullName>Balance sheet hedging</fullName>
            </value>
            <value>
                <fullName>Repatriation of revenues from investments</fullName>
            </value>
            <value>
                <fullName>Portfolio netting</fullName>
            </value>
            <value>
                <fullName>Other not related to identifiable goods or services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CNT_B2B_Purpose.cls
public class CNT_B2B_Purpose {
    @AuraEnabled(cacheable=true)
    public static ReturnValue getPurposes(){
        ReturnValue response = null;
        try {
            Map<String, Object> value = new Map<String, Object>();          
            List<String> picklistValues = new List<String>();
            Schema.DescribeFieldResult fieldResult = Purpose_of_Payment__mdt.PUR_PCK_Purpose__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for( Schema.PicklistEntry picklistVal : ple){
                picklistValues.add(picklistVal.getLabel());
            }
            value.put('picklistValues', picklistValues);      
            response = new ReturnValue(true, value);
        } catch (Exception e) {
            System.debug('CNT_B2B_Purpose.getPurposes: ' + e.getMessage() + ', in line: ' + e.getLineNumber());
            response = new ReturnValue(false, null, e.getMessage());
        }
        return response;
    }

}