force-app/main/default/objects/SGN_User__c/SGN_User__c.object-meta.xml
<CustomObject>
    <label>Signature User</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signature Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SGN_User__c/fields/SGN_ELCK_RelatedSign__c.field-meta.xml
<CustomField>
    <fullName>SGN_ELCK_RelatedSign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Signature</label>
    <referenceTo>SNG_Payment__c</referenceTo>
    <relationshipLabel>Signature Users</relationshipLabel>
    <relationshipName>Signature_Users</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SGN_User__c/fields/SGN_TXT_GlobalId__c.field-meta.xml
<CustomField>
    <fullName>SGN_TXT_GlobalId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Global Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SGN_User__c/fields/SNG_OTP_ID__c.field-meta.xml
<CustomField>
    <fullName>SNG_OTP_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>OTP ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SNG_Payment__c/SNG_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment Signature</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Signatures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SNG_Payment__c/fields/SGN_TXT_IdPayment__c.field-meta.xml
<CustomField>
    <fullName>SGN_TXT_IdPayment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

zip/mdapiOTVLwr/unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>USER_TXT_GlobalId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Global Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/WS_B2B_OTP_Strategic_Test.cls
@isTest
public class WS_B2B_OTP_Strategic_Test {
    
    @TestSetup
    static void setup(){
        DataFactory.getCustomSettingCryptoKey(true);
        DataFactory.createWsConfigurationSetting(true); 
    }
    
    @isTest
    static void inputInitiateOTP_constructor_Test(){
        User u = DataFactory.getRunningUser(true);
        system.runAs(u){
            WS_B2B_OTP_Strategic.InputInitiateOTP inputTest = new WS_B2B_OTP_Strategic.InputInitiateOTP('beneficiaryName', 'beneficiaryAccount', 
                                                                                                   'paymentId', 'debitAmount', 'fees',
                                                                                                  'exchangeRate', 'paymentAmount');
          }
        
    }
    
    @isTest
    static void identifierType_userNoGlobalId_Test(){
        
       User currentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        
        System.runAs(currentUser){
            // Get the support profile
            Profile p = [SELECT Id FROM Profile WHERE Name='Support']; 
            UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        
            // Create a support user
            User supportUser = new User(Alias = 'scau', Email='supportUser@testorg.com', 
                                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id, UserRoleId = portalRole.Id,
                                TimeZoneSidKey='America/Los_Angeles', UserName='standardusergts@acmesupport.com', isActive = true);
            insert supportUser;

            WS_B2B_OTP_Strategic.IdentifierType idType = new WS_B2B_OTP_Strategic.IdentifierType(supportUser);            
        }
      
    }
    
    @isTest
    static void identifierType_noUser_Test(){
        
       User nullUser = null;
       WS_B2B_OTP_Strategic.IdentifierType idType = new WS_B2B_OTP_Strategic.IdentifierType(nullUser);
        
    }
    
    @isTest
    static void getOTP_Test(){
        
        WS_B2B_OTP_Strategic.getOTP('beneficiaryName', 'beneficiaryAccount', 'paymentId', 
                                    'debitAmount', 'fees', 'exchangeRate', 'paymentAmount' );
        
    }
    
    @isTest
    static void storeOTPId_Test(){
        User u = DataFactory.getRunningUser(true);
        system.runAs(u){
            String paymentID = 'paymentID';
            SNG_Payment__c sngPay = new SNG_Payment__c();
            sngPay.SGN_TXT_IdPayment__c = paymentID;
            insert sngPay;
            
            String userID = Global_Utilities.getUserData('').USER_TXT_GlobalId__c;
            
            SGN_User__c user = new SGN_User__c();
            user.SNG_OTP_ID__c = 'test';
            user.SGN_TXT_GlobalId__c = userID;
            user.SGN_ELCK_RelatedSign__c = sngPay.Id;
            
            insert user;
            
            WS_B2B_OTP_Strategic.storeOTPId('otpId', paymentID);
        }
        
    }
    
}