force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/PAY_TXT_ClientReference__c.field-meta.xml
<CustomField>
    <fullName>PAY_TXT_ClientReference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Client Reference</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PAY_TXT_PaymentId__c.field-meta.xml
<CustomField>
    <fullName>PAY_TXT_PaymentId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Payment Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HANDLER_Payment.cls
public class HANDLER_Payment {

    public static ReturnValue upsertPayment(WRAPPER_PAY_PaymentDraft paymentDraft){
        ReturnValue response;
        try{  
            if(paymentDraft != null && String.isNotBlank(paymentDraft.paymentId)){   
       		    Payment__c payment = new Payment__c ();
           	    payment.PAY_TXT_PaymentId__c = paymentDraft.paymentId;
                payment.PAY_TXT_ClientReference__c = String.isNotBlank(paymentDraft.reference) ? paymentDraft.reference : '';       
        	    database.upsert(payment, Payment__c.Fields.PAY_TXT_PaymentId__c);
                response = new ReturnValue (true);
            }
            else{
                response = new ReturnValue (false, 'Payment Id cannot be null');
            }
    	}catch (Exception e) {
            response = new ReturnValue (false,  e.getMessage());
            System.debug('HANDLER_Payment.upsertPayment: ' + e.getMessage() + ' in line ' + e.getLineNumber());
        }
        return response;
    }
}