force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/PAY_TXT_ClientReference__c.field-meta.xml
<CustomField>
    <fullName>PAY_TXT_ClientReference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Client Reference</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PAY_TXT_PaymentId__c.field-meta.xml
<CustomField>
    <fullName>PAY_TXT_PaymentId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Payment Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SGN_Group__c/SGN_Group__c.object-meta.xml
<CustomObject>
    <label>Signature Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signature Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SGN_Group__c/fields/SGN_ELCK_RelatedSign__c.field-meta.xml
<CustomField>
    <fullName>SGN_ELCK_RelatedSign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Sign</label>
    <referenceTo>SNG_Payment__c</referenceTo>
    <relationshipLabel>Signature Groups</relationshipLabel>
    <relationshipName>Signature_Groups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SGN_User__c/SGN_User__c.object-meta.xml
<CustomObject>
    <label>Signature User</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signature Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SGN_User__c/fields/SGN_ELCK_RelatedSign__c.field-meta.xml
<CustomField>
    <fullName>SGN_ELCK_RelatedSign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Signature</label>
    <referenceTo>SNG_Payment__c</referenceTo>
    <relationshipLabel>Signature Users</relationshipLabel>
    <relationshipName>Signature_Users</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SGN_User__c/fields/SGN_ELCK_RelatedUser__c.field-meta.xml
<CustomField>
    <fullName>SGN_ELCK_RelatedUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Signature_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SNG_Group_User__c/SNG_Group_User__c.object-meta.xml
<CustomObject>
    <label>Signature Group User</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Signature Group User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signature Group Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SNG_Group_User__c/fields/SGN_ELCK_RelatedGroup__c.field-meta.xml
<CustomField>
    <fullName>SGN_ELCK_RelatedGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signature Group</label>
    <referenceTo>SGN_Group__c</referenceTo>
    <relationshipLabel>Signature Group Users</relationshipLabel>
    <relationshipName>Signature_Group_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SNG_Group_User__c/fields/SGN_ELCK_RelatedUser__c.field-meta.xml
<CustomField>
    <fullName>SGN_ELCK_RelatedUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signature User</label>
    <referenceTo>SGN_User__c</referenceTo>
    <relationshipLabel>Signature Group Users</relationshipLabel>
    <relationshipName>Signature_Group_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SNG_Payment__c/SNG_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment Signature</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Signatures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HANDLER_CustomNotification.cls
/*----------------------------------------------------------------------------------
Author:         Antonio Duarte
Company:        Deloitte
Description:    Class that handles the custom notification delivery
History
<Date>          <Author>                <Description>
05/10/2020      Antonio Duarte          Initial version     
09/12/2020      Héctor Estivalis        REDO   
----------------------------------------------------------------------------------*/
global without sharing class HANDLER_CustomNotification {
    
    global static void sendPaymentNotification(String paymentId, String notificationType){
        try{
            String notifTypeId = [SELECT Id FROM CustomNotificationType WHERE CustomNotifTypeName = 'Custom Community Notification' LIMIT 1]?.Id;
            Payment__c payment = [SELECT Id, PAY_TXT_PaymentId__c, PAY_TXT_ClientReference__c, CreatedById FROM Payment__c WHERE PAY_TXT_PaymentId__c = :paymentId LIMIT 1];

            if (payment != null){
                List<Id> receptorIds = getReceptors (payment, notificationType);
                String body          = getBody (payment.PAY_TXT_ClientReference__c, notificationType);
                String title         = getTitle ();
                
                Map<String, Object> params = new Map<String, Object>();
                params.put('RecipientIDs', receptorIds);
                params.put('NotificationBody', body);
                params.put('NotificationTitle', title);
                params.put('TargetID', payment.Id);
                params.put('NotifTypeID', notifTypeId);
                
                if(!receptorIds.isEmpty()){
                    Flow.Interview.Send_Custom_Notification sendNotificationFlow = new Flow.Interview.Send_Custom_Notification(params);
                    sendNotificationFlow.start();
                }
            }
        }catch(Exception e){
            System.debug('Error sending the custom notification');
        }
    }

    @TestVisible
    private static List<Id> getReceptors (Payment__c payment, String notificationType){
        List<Id> response = new List<Id>();
        if(notificationType == 'Pending'){
            List<SNG_Group_User__c> signers = [SELECT SGN_ELCK_RelatedUser__r.SGN_ELCK_RelatedUser__r.Id FROM SNG_Group_User__c WHERE SGN_ELCK_RelatedGroup__r.SGN_ELCK_RelatedSign__r.SGN_TXT_IdPayment__c = :payment.PAY_TXT_PaymentId__c];
            for (SNG_Group_User__c u : signers){
                if(u.SGN_ELCK_RelatedUser__c != null && u.SGN_ELCK_RelatedUser__r.SGN_ELCK_RelatedUser__c != null){
                    response.add(u.SGN_ELCK_RelatedUser__r.SGN_ELCK_RelatedUser__r.Id);
                }
            }
        }
        else {
            response.add(payment.CreatedById);
        }
        system.debug('getReceptors:' + response);    
        return response;
    }
    
    @TestVisible
    private static String getBody (String clientReference, String notificationType){
        String response = '';
        clientReference = clientReference == null ? '[client_ref]' : clientReference;
        String userName = Userinfo.getName();
        Switch on notificationType {
            when 'Pending'{
                response = System.label.PAY_NotificationPaymentPending.replace('[client_ref]', clientReference);
            }
            when 'Reject'{
                response = System.label.PAY_NotificationPaymentRejected.replace('[client_ref]', clientReference).replace('[Authorizator]', userName);
            }
            when 'Review'{
                response = System.label.PAY_NotificationPaymentReview.replace('[client_ref]', clientReference).replace('[Authorizator]', userName);
            }
            when 'Completed'{
                response = System.label.PAY_NotificationPaymentAuthorized.replace('[client_ref]', clientReference);
            }
        }
        system.debug('getBody:' + response);
        return response;
    }
    
    @TestVisible
    private static String getTitle (){
        String response = System.label.Payments;
        system.debug('getTitle:' + response);
        return response;
    }    
}