force-app/main/default/objects/CNT_ApiConfiguration__c/CNT_ApiConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to handle api calls</description>
    <label>API Configuration</label>
</CustomObject>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>CNT_Endpoint__c</fullName>
    <description>Endpoint of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Endpoint of the service</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_HTTPMethod__c.field-meta.xml
<CustomField>
    <fullName>CNT_HTTPMethod__c</fullName>
    <description>Http Method of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Http Method of the service</inlineHelpText>
    <label>HTTP Method</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_Service__c.field-meta.xml
<CustomField>
    <fullName>CNT_Service__c</fullName>
    <description>Service of the endpoint</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Service of the endpoint</inlineHelpText>
    <label>Service</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SNG_Payment__c/SNG_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment Signature</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Signatures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SNG_Payment__c/fields/SGN_TXT_IdPayment__c.field-meta.xml
<CustomField>
    <fullName>SGN_TXT_IdPayment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CNT_SwiftPaymentTable_Test.cls
/*----------------------------------------------------------------------------------
Author:         R. Alexander Cervino
Company:        Deloitte
Description:    Test class for CNT_SwiftPaymentTable
History
<Date>			<Author>		<Description>
12/12/2019		R. Alexander Cervino     Initial version
----------------------------------------------------------------------------------*/
@isTest
public class CNT_SwiftPaymentTable_Test {
    
    @testSetup
    static void setup(){
        DataFactory.createWsConfigurationSetting(true);
    }
    @isTest
    static void main(){
        Test.setMock(HttpCalloutMock.class, new CNT_SwiftPaymentTable_MockHttp());
        CNT_ApiConfiguration__c configWs = new CNT_ApiConfiguration__c(Name = 'CNT_UETRPublic',
                                                                       CNT_Endpoint__c = 'https://api.sandbox.mulesoft.onetrade.santander.com/onetrade/{{entorno}}/api/v1/payments_tracker_public_web/{payment_Id}',
                                                                       CNT_HTTPMethod__c = 'GET',
                                                                       CNT_Service__c = 'mulesoft');
        insert configWs;
        
        SNG_Payment__c payment = new SNG_Payment__c(SGN_TXT_IdPayment__c='Test');
		insert payment;
        
        Test.startTest();
        
        
        CNT_SwiftPaymentTable.getFilteredData('hola');
        CNT_SwiftPaymentTable.downloadMT103Doc('Test');
        try{
            CNT_SwiftPaymentTable.encryptData('Test');
        }catch(Exception e){
            system.debug(e);
        }
        
        CNT_SwiftPaymentTable.removeMT103('Test');
        CNT_SwiftPaymentTable.getDateAndTime('10/10/2020');
        CNT_SwiftPaymentTable.getUETR('Test');
        Test.stopTest();
	}
}