force-app/main/default/objects/CNT_ApiConfiguration__c/CNT_ApiConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to handle api calls</description>
    <label>API Configuration</label>
</CustomObject>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>CNT_Endpoint__c</fullName>
    <description>Endpoint of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Endpoint of the service</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_HTTPMethod__c.field-meta.xml
<CustomField>
    <fullName>CNT_HTTPMethod__c</fullName>
    <description>Http Method of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Http Method of the service</inlineHelpText>
    <label>HTTP Method</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__mdt/fields/COU_PCK_Language__c.field-meta.xml
<CustomField>
    <fullName>COU_PCK_Language__c</fullName>
    <description>Language codes</description>
    <label>COU_PCK_Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en_US</fullName>
                <default>true</default>
                <label>en_US</label>
            </value>
            <value>
                <fullName>es</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>pt_BR</fullName>
            </value>
            <value>
                <fullName>it</fullName>
            </value>
            <value>
                <fullName>de</fullName>
            </value>
            <value>
                <fullName>ja</fullName>
            </value>
            <value>
                <fullName>sv</fullName>
            </value>
            <value>
                <fullName>ko</fullName>
            </value>
            <value>
                <fullName>zh_TW</fullName>
            </value>
            <value>
                <fullName>zh_CN</fullName>
            </value>
            <value>
                <fullName>nl_NL</fullName>
            </value>
            <value>
                <fullName>da</fullName>
            </value>
            <value>
                <fullName>th</fullName>
            </value>
            <value>
                <fullName>fi</fullName>
            </value>
            <value>
                <fullName>ru</fullName>
            </value>
            <value>
                <fullName>es_MX</fullName>
            </value>
            <value>
                <fullName>no</fullName>
            </value>
            <value>
                <fullName>hu</fullName>
            </value>
            <value>
                <fullName>pl</fullName>
            </value>
            <value>
                <fullName>cs</fullName>
            </value>
            <value>
                <fullName>tr</fullName>
            </value>
            <value>
                <fullName>in</fullName>
            </value>
            <value>
                <fullName>ro</fullName>
            </value>
            <value>
                <fullName>vi</fullName>
            </value>
            <value>
                <fullName>uk</fullName>
            </value>
            <value>
                <fullName>iw</fullName>
            </value>
            <value>
                <fullName>el</fullName>
            </value>
            <value>
                <fullName>bg</fullName>
            </value>
            <value>
                <fullName>en_GB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__mdt/fields/COU_PCK_Locale__c.field-meta.xml
<CustomField>
    <fullName>COU_PCK_Locale__c</fullName>
    <description>Locale codes</description>
    <label>COU_PCK_Locale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en_GB</fullName>
                <default>true</default>
                <label>en_GB</label>
            </value>
            <value>
                <fullName>es_ES</fullName>
            </value>
            <value>
                <fullName>fr_FR</fullName>
            </value>
            <value>
                <fullName>pt_BR</fullName>
            </value>
            <value>
                <fullName>it_IT</fullName>
            </value>
            <value>
                <fullName>de_DE</fullName>
            </value>
            <value>
                <fullName>sq_AL</fullName>
            </value>
            <value>
                <fullName>ar_DZ</fullName>
            </value>
            <value>
                <fullName>ar_BH</fullName>
            </value>
            <value>
                <fullName>ar_EG</fullName>
            </value>
            <value>
                <fullName>ar_IQ</fullName>
            </value>
            <value>
                <fullName>ar_JO</fullName>
            </value>
            <value>
                <fullName>ar_KW</fullName>
            </value>
            <value>
                <fullName>ar_LB</fullName>
            </value>
            <value>
                <fullName>ar_LY</fullName>
            </value>
            <value>
                <fullName>ar_MA</fullName>
            </value>
            <value>
                <fullName>ar_OM</fullName>
            </value>
            <value>
                <fullName>ar_QA</fullName>
            </value>
            <value>
                <fullName>ar_SA</fullName>
            </value>
            <value>
                <fullName>ar_SD</fullName>
            </value>
            <value>
                <fullName>ar_SY</fullName>
            </value>
            <value>
                <fullName>ar_TN</fullName>
            </value>
            <value>
                <fullName>ar_AE</fullName>
            </value>
            <value>
                <fullName>ar_YE</fullName>
            </value>
            <value>
                <fullName>hy_AM</fullName>
            </value>
            <value>
                <fullName>az_AZ</fullName>
            </value>
            <value>
                <fullName>bn_BD</fullName>
            </value>
            <value>
                <fullName>eu_ES</fullName>
            </value>
            <value>
                <fullName>be_BY</fullName>
            </value>
            <value>
                <fullName>bs_BA</fullName>
            </value>
            <value>
                <fullName>en_US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

zip/mdapiOTVLwr/unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>USER_CHK_CashNexus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cash Nexus User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>USER_NumberFormat__c</fullName>
        <description>Number format of the user</description>
        <inlineHelpText>Enter a number format for the user.</inlineHelpText>
        <label>Number format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>###.###.###,##</fullName>
                    <default>true</default>
                    <label>###.###.###,##</label>
                </value>
                <value>
                    <fullName>###,###,###.##</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>USER_PCK_Language__c</fullName>
        <description>Languages displayed in the My Settings section of the Community</description>
        <label>USER_PCK_Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Language</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_DateFormat__c</fullName>
        <description>Date format for the user</description>
        <inlineHelpText>Enter a date format.</inlineHelpText>
        <label>Date format</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>dd/MM/yyyy</fullName>
                    <default>true</default>
                    <label>dd/MM/yyyy</label>
                </value>
                <value>
                    <fullName>MM/dd/yyyy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>en_US</fullName>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>es</fullName>
        <label>Spanish</label>
    </customValue>
    <customValue>
        <fullName>pt_BR</fullName>
        <label>Portuguese (Brazil)</label>
    </customValue>
    <customValue>
        <fullName>pl</fullName>
        <label>Polish</label>
    </customValue>
    <customValue>
        <fullName>pt_PT</fullName>
        <label>Portuguese (European)</label>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CNT_UserSettingsController.cls
/*----------------------------------------------------------------------------------
Author:         Joaquín Vera Vallés
Company:        Deloitte
Description:    Controller of User's my settings screen.
Test Class:     CNT_UserSettings_Test
History
<Date>			<Author>		<Description>
28/02/2020		Joaquín Vera Vallés     Initial version
----------------------------------------------------------------------------------*/
public with sharing class CNT_UserSettingsController 
{
   

    @AuraEnabled
    public static Map<String,String> getUserSettings()
    {
        User currentUser = null;

        if( Schema.sObjectType.User.fields.Id.isAccessible() &&
            Schema.sObjectType.User.fields.User_DateFormat__c.isAccessible() &&
            Schema.sObjectType.User.fields.USER_NumberFormat__c.isAccessible() &&
            Schema.sObjectType.User.fields.USER_CHK_CashNexus__c.isAccessible())
        {
            currentUser = [SELECT Id, User_DateFormat__c, USER_NumberFormat__c, USER_CHK_CashNexus__c FROM User WHERE Id = :UserInfo.getUserId()];
        }
        
        Map<String, String> userData = new Map<String, String>();

        List<PicklistEntry> timeZoneList = Schema.SObjectType.User.fields.TimeZoneSidKey.picklistValues;
        Schema.PicklistEntry[] languageList = Schema.SObjectType.User.fields.LanguageLocaleKey.PicklistValues;
        Schema.PicklistEntry[] currenciesList = Schema.SObjectType.User.fields.DefaultCurrencyIsoCode.PicklistValues;
        
        // Mapping of time Zones
        String userTimeZone = mapData(timeZoneList, UserInfo.getTimeZone().toString());


        // Mapping of languages
        String userLanguage = mapData(languageList, UserInfo.getLanguage());

        // Mapping of currencies
        String userCurrency = mapData(currenciesList, UserInfo.getDefaultCurrency());

        // Adding data to the map of user data
        userData.put('TimeZone', userTimeZone);
        // userData.put('Locale', userLocale);
        userData.put('Language', userLanguage);
        userData.put('Currency', userCurrency);

        if(currentUser != null) 
        {
            userData.put('DateFormat', currentUser.User_DateFormat__c);
            userData.put('NumberFormat', currentUser.USER_NumberFormat__c);
            userData.put('isCashNexus', String.valueOf(currentUser.USER_CHK_CashNexus__c));
        }
        return userData;
    }


    @AuraEnabled
    public static String getPicklistValues()
    {
        Map<String,List<Object>> data = new Map<String,List<Object>>();

        data.put('TimeZoneList', ( Object[])Schema.SObjectType.User.fields.TimeZoneSidKey.picklistValues);
        data.put('LanguageList', ( Object[])Schema.SObjectType.User.fields.USER_PCK_Language__c.PicklistValues);
        data.put('CurrencyList', ( Object[])Schema.SObjectType.User.fields.DefaultCurrencyIsoCode.PicklistValues);
        data.put('NumberFormatList', ( Object[])Schema.SObjectType.User.fields.USER_NumberFormat__c .PicklistValues);
        data.put('DateFormatList', ( Object[])Schema.SObjectType.User.fields.User_DateFormat__c .PicklistValues);
        System.debug(JSON.serialize(data.get('NumberFormatList')));
        return JSON.serialize(data);

    }

    @AuraEnabled
    public static boolean saveData(Map<String,String> userInfoCmp)
    {
        
        User currentUser = null;

        if(userInfoCmp.size() > 0) 
        {
                currentUser = [SELECT Id, User_DateFormat__c, USER_NumberFormat__c, DefaultCurrencyIsoCode, CurrencyIsoCode, TimeZoneSidKey, LanguageLocaleKey, LocaleSidKey FROM User WHERE Id = :UserInfo.getUserId() ];
                
        }
        if(currentUser != null) 
        {
            Map<String, Schema.PicklistEntry[]> picklistValues = (Map<String, Schema.PicklistEntry[]>) JSON.deserialize(getPicklistValues(), Map<String, Schema.PicklistEntry[]>.class);

            currentUser.User_dateFormat__c = userInfoCmp.get('DateFormat');
            currentUser.USER_NumberFormat__c = userInfoCmp.get('NumberFormat');
            currentUser.CurrencyIsoCode = mapValue(picklistValues.get('CurrencyList'), userInfoCmp.get('Currency'));
            currentUser.DefaultCurrencyIsoCode = mapValue(picklistValues.get('CurrencyList'), userInfoCmp.get('Currency'));
            currentUser.TimeZoneSidKey = mapValue(picklistValues.get('TimeZoneList'), userInfoCmp.get('TimeZone'));
            System.debug('Currency mapped: ' + currentUser.CurrencyIsoCode);
            String languageMapped = mapValue(picklistValues.get('LanguageList'), userInfoCmp.get('Language'));
            if(languageMapped != currentUser.LanguageLocaleKey) 
            {
                List<Country__mdt> matchingMetadata = [SELECT COU_PCK_Language__c, COU_PCK_Locale__c FROM Country__mdt WHERE COU_PCK_Language__c = :languageMapped LIMIT 1 ];
                if(matchingMetadata.size() > 0) 
                {
                    if(matchingMetadata.get(0).COU_PCK_Locale__c != null) 
                    {
                        if(matchingMetadata.get(0).COU_PCK_Language__c == 'en_US')
                        {
                            currentUser.LocaleSidKey = 'en_US';
                        }
                        else
                        {
                            currentUser.LocaleSidKey = matchingMetadata.get(0).COU_PCK_Locale__c;
                        }
                    }
                }
                currentUser.LanguageLocaleKey = languageMapped;                
            }
        }

        try 
        {
            System.debug(JSON.serialize(currentUser));
            update currentUser;

        } catch(DmlException e) 
        {
            System.debug(e);
            return false;
        }

        return true;
    }



    public static String mapData(Schema.PicklistEntry[] dataList, String toSearch)
    {
        for(PicklistEntry data : dataList) 
        {
            if(data.value.equals(toSearch)) 
            {
                return data.label;
            }
        }
        return '';
    }

    public static String mapValue(Schema.PicklistEntry[] dataList, String toSearch)
    {
        for(PicklistEntry data : dataList) 
        {
            if(data.label.equals(toSearch)) 
            {
                return data.value;
            }
        }
        return '';
    }

    @AuraEnabled
    public static String changePassword (String oldPasswordParam, String newPasswordParam)
    {

        CNT_ApiConfiguration__c configWs = CNT_ApiConfiguration__c.getValues('CNT_UpdatePassword');
        String endpoint = configWs.CNT_Endpoint__c.replace('{New}', newPasswordParam).replace('{Old}', oldPasswordParam);
        String response = Global_IntegrationWrapper.launchHttp('', endpoint, configWs.CNT_HTTPMethod__c);
        return response;
    }

}