force-app/main/default/objects/CNT_ApiConfiguration__c/CNT_ApiConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to handle api calls</description>
    <label>API Configuration</label>
</CustomObject>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>CNT_Endpoint__c</fullName>
    <description>Endpoint of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Endpoint of the service</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_HTTPMethod__c.field-meta.xml
<CustomField>
    <fullName>CNT_HTTPMethod__c</fullName>
    <description>Http Method of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Http Method of the service</inlineHelpText>
    <label>HTTP Method</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CNT_LogAdminSearchController.cls
public class CNT_LogAdminSearchController {
    
    @AuraEnabled
    public static List<WRAPPER_LogAdminSearch> getLogs(){
        
        return getLogsData();
    }
    
    @AuraEnabled
    public static List<CNT_LogAdminSearchDataWrapper> getLogsMock(){
        
        return generateMockData();
    }
    
    public static List<CNT_LogAdminSearchDataWrapper> generateMockData() {
        
        List<CNT_LogAdminSearchDataWrapper> data = new List<CNT_LogAdminSearchDataWrapper>();
        for(Integer i = 0; i<220; i++){
            CNT_LogAdminSearchDataWrapper data1 = new CNT_LogAdminSearchDataWrapper('25/11/2019, 12:35', '02101626092254', 'Miguel Admin Temporal ' + i, 'User Login : OK 02101626092254 Miguel Admin Temporal');
            data.add(data1);
        }
        
        return data;
        
    }
    
    /*----------------------------------------------------------------------------------
Author:         Guillermo Giral
Company:        Deloitte
Description:    Method that retrieves the data from the input source
History
<Date>			<Author>		            <Description>
29/01/2020		Guillermo Giral             Initial version
----------------------------------------------------------------------------------*/
    public static List<WRAPPER_LogAdminSearch> getLogsData(){
        try {       
            CNT_ApiConfiguration__c configWs = CNT_ApiConfiguration__c.getValues('CNT_GetLogs');
            String response = Global_IntegrationWrapper.launchHTTP('', configWs.CNT_Endpoint__c, configWs.CNT_HTTPMethod__c);
            
            if (Test.isRunningTest() ) {
                response='['+
                    '  {'+
                    '    \"action\": \"User Login : OK 02101626092254 Miguel Admin Temporal\",'+
                    '    \"logDate\": \"25/11/2019, 12:35\",'+
                    '    \"name\": \"Miguel Admin Temporal 0\",'+
                    '    \"userId\": \"02101626092254\"'+
                    '  },'+
                    '  {'+
                    '    \"action\": \"User Login : OK 02101626092254 Miguel Admin Temporal\",'+
                    '    \"logDate\": \"25/11/2019, 12:35\",'+
                    '    \"name\": \"Miguel Admin Temporal 1\",'+
                    '    \"userId\": \"02101626092254\"'+
                    '  },'+
                    '  {'+
                    '    \"action\": \"User Login : OK 02101626092254 Miguel Admin Temporal\",'+
                    '    \"logDate\": \"25/11/2019, 12:35\",'+
                    '    \"name\": \"Miguel Admin Temporal 2\",'+
                    '    \"userId\": \"02101626092254\"'+
                    '  },'+
                    '  {'+
                    '    \"action\": \"User Login : OK 02101626092254 Miguel Admin Temporal\",'+
                    '    \"logDate\": \"25/11/2019, 12:35\",'+
                    '    \"name\": \"Miguel Admin Temporal 3\",'+
                    '    \"userId\": \"02101626092254\"'+
                    '  }'+
                    ']';
            }
            
            
            if (String.isNotBlank(response)) {
                List<WRAPPER_LogAdminSearch> listLogs = WRAPPER_LogAdminSearch.parse(response);
                return listLogs;
            } else {
                //FALTA LA LABEL
                throw new customException(Label.getDataError);
            }
        } catch (Exception e) {
            System.debug('CNT_LogAdminSearchController.getLogsData: ' + e.getMessage());
            throw new customException(e.getMessage());
        }
    }
    
    //WRAPPER OF LOGS DATA
    public class CNT_LogAdminSearchDataWrapper {
        @AuraEnabled public String logDate                      {get;set;}
        @AuraEnabled public String userId                       {get;set;}
        @AuraEnabled public String name                         {get;set;}
        @AuraEnabled public String action                       {get;set;}
        
        public CNT_LogAdminSearchDataWrapper(String logDate,String userId,String name,String action){
            this.logDate = logDate;
            this.userId = userId;
            this.name = name;
            this.action = action;
        }
    }   
    
}