force-app/main/default/objects/CNT_ApiConfiguration__c/CNT_ApiConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to handle api calls</description>
    <label>API Configuration</label>
</CustomObject>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>CNT_Endpoint__c</fullName>
    <description>Endpoint of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Endpoint of the service</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_HTTPMethod__c.field-meta.xml
<CustomField>
    <fullName>CNT_HTTPMethod__c</fullName>
    <description>Http Method of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Http Method of the service</inlineHelpText>
    <label>HTTP Method</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_Service__c.field-meta.xml
<CustomField>
    <fullName>CNT_Service__c</fullName>
    <description>Service of the endpoint</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Service of the endpoint</inlineHelpText>
    <label>Service</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/tokenPlatform__c.field-meta.xml
<CustomField>
    <fullName>tokenPlatform__c</fullName>
    <description>Indicates if the platform is GTS or SANDIGITAL</description>
    <encryptionScheme>None</encryptionScheme>
    <label>tokenPlatform</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/tokenUser__c.field-meta.xml
<CustomField>
    <fullName>tokenUser__c</fullName>
    <description>Indicates if the user is nexus, local or platform</description>
    <encryptionScheme>None</encryptionScheme>
    <label>tokenUser</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SNG_Payment__c/SNG_Payment__c.object-meta.xml
<CustomObject>
    <label>Payment Signature</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Signatures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SNG_Payment__c/fields/SGN_TXT_IdPayment__c.field-meta.xml
<CustomField>
    <fullName>SGN_TXT_IdPayment__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Payment Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WS_B2B_OTP_Test.cls
/*----------------------------------------------------------------------------------
Author:         A. Borraz
Company:        Deloitte
History
<Date>			<Author>		<Description>
24/11/2020		A. Borraz     Initial version
----------------------------------------------------------------------------------*/

@isTest
public class WS_B2B_OTP_Test {
    
    @testSetup  
    static void setup(){
        DataFactory.createWsConfigurationSetting(true);
		main();
    }
   
    @isTest
    static void main(){
        CNT_ApiConfiguration__c configWs = new CNT_ApiConfiguration__c(Name = 'WS_TransferFees',
                                                                       CNT_Endpoint__c = 'https://api.sandbox.mulesoft.onetrade.santander.com/onetrade/cert/api/v1/prices',
                                                                       CNT_HTTPMethod__c = 'GET',
                                                                       tokenPlatform__c = 'GTS',
                                                                       tokenUser__c = 'nexus',
                                                                       CNT_Service__c = 'mulesoft');
        insert configWs;
        
        SNG_Payment__c payment = new SNG_Payment__c(SGN_TXT_IdPayment__c='Test');
		insert payment;
        
        Test.setMock(HttpCalloutMock.class, new WS_B2B_OTP_Test_MockHttp());
        Test.startTest();
        
        WS_B2B_OTP.initiateOTP initiateOTP = new WS_B2B_OTP.initiateOTP();
        initiateOTP.scaUid = 'Test';
        
        WS_B2B_OTP.AuthenticateRequest AuthenticateRequest = new WS_B2B_OTP.AuthenticateRequest();
        AuthenticateRequest.embeddedSystem = 'Test';
        AuthenticateRequest.serviceId = 'Test';
        AuthenticateRequest.metaData = 'Test';
        WS_B2B_OTP.AuthenticateRequest AuthenticateRequest_sub = new WS_B2B_OTP.AuthenticateRequest('Test','Test','Test');
        
        WS_B2B_OTP.DocumentId DocumentId = new WS_B2B_OTP.DocumentId();
        DocumentId.documentType = 'Test';
		DocumentId.documentNumber = 'Test';
        
        WS_B2B_OTP.IdentifierType IdentifierType = new WS_B2B_OTP.IdentifierType();
        IdentifierType.emailAddress = 'Test';
		IdentifierType.documentId = DocumentId;
        IdentifierType.aliasIdentity = 'Test';    
        IdentifierType.phoneNumber = 'Test';  

        WS_B2B_OTP.InputInitiateOTP InputInitiateOTP = new WS_B2B_OTP.InputInitiateOTP();
        InputInitiateOTP.identifierType = IdentifierType;
		InputInitiateOTP.embeddedSystem = 'Test';        

        WS_B2B_OTP.jwtValidate jwtValidate = new WS_B2B_OTP.jwtValidate();
        jwtValidate.jti = 'Test';
		jwtValidate.iat = 'Test';
        jwtValidate.status = 'Test';    
        jwtValidate.scaUid = 'Test';  
        jwtValidate.config_uid = 'Test';  

        
        WS_B2B_OTP.validateOTP validateOTP = new WS_B2B_OTP.validateOTP();
        validateOTP.jwt = jwtValidate;
		validateOTP.validateResult = 'Test';      
		validateOTP.codeAuthenticateResult = 'Test';  
		validateOTP.scaId = 'Test';  
		validateOTP.token = 'Test';
		validateOTP.timestamp = 'Test';  
        try{
          WS_B2B_OTP.validateOTP validateOTP_sub = new WS_B2B_OTP.validateOTP('Test\\.Test');  
        }catch(Exception e){
            system.debug(e);
        }  
        
        
        WS_B2B_OTP.InputValidateOTP InputValidateOTP = new WS_B2B_OTP.InputValidateOTP();
        InputValidateOTP.scaUid = 'Test';
		InputValidateOTP.scaSecret = 'Test';  
        
        WS_B2B_OTP.InputValidateOTP InputValidateOTP_sub = new WS_B2B_OTP.InputValidateOTP('Test','Test');
      
        
       
        Test.stopTest();
    }
    
    @isTest
    public static void getOTPTest(){
        WS_B2B_OTP.getOTP('ES','09090909');
    }
    
 	@isTest
    public static void validateOTPTest(){
        WS_B2B_OTP.validateOTP('Test','Test','ES','09090909');
    }
    
 	@isTest
    public static void storeOTPIdTest(){
        WS_B2B_OTP.storeOTPId('Test','Test');
    }
    
 	@isTest
    public static void obtainOTPIdTest(){
        WS_B2B_OTP.obtainOTPId('Test');
    }
}