force-app/main/default/objects/CNT_ApiConfiguration__c/CNT_ApiConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to handle api calls</description>
    <label>API Configuration</label>
</CustomObject>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>CNT_Endpoint__c</fullName>
    <description>Endpoint of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Endpoint of the service</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_HTTPMethod__c.field-meta.xml
<CustomField>
    <fullName>CNT_HTTPMethod__c</fullName>
    <description>Http Method of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Http Method of the service</inlineHelpText>
    <label>HTTP Method</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_Service__c.field-meta.xml
<CustomField>
    <fullName>CNT_Service__c</fullName>
    <description>Service of the endpoint</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Service of the endpoint</inlineHelpText>
    <label>Service</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ControllerTransferFees_Test.cls
/*
Author:         Andrea Martin
Company:        Deloitte
History:
<Date>          <Author>            <Description>
24/02/2021      Andrea Martin             Initial version
*/
@isTest
public class ControllerTransferFees_Test {

    @testSetup
    static void setup () {
        DataFactory.getCustomSettingCryptoKey(true);
        DataFactory.createWsConfigurationSetting(true);
    }

    @isTest
    static void transferFeesExecute_Test() {
        try {
            CNT_ApiConfiguration__c configWs = new CNT_ApiConfiguration__c(
                Name = 'WS_TransferFees',
                CNT_Endpoint__c = 'WS_TransferFees',
                CNT_HTTPMethod__c = 'GET',
                CNT_Service__c = 'mulesoft'
            );
            insert configWs;
           Test.setMock(HttpCalloutMock.class, new WS_TransferFees_Test_MockHttp());   

            WRAPPER_PAY_PaymentDraft_Mock mock = new WRAPPER_PAY_PaymentDraft_Mock();
            WRAPPER_PAY_PaymentDraft paymentDraft = mock.bookToBookDraft(true);
            Test.startTest();
            ControllerTransferFees.transferFeesExecute(paymentDraft);
            Test.stopTest();
        } catch (Exception e) {
            System.debug('ControllerTransferFees_Test.transferFeesExecute_Test: ' + e.getMessage() + ', in line: ' + e.getLineNumber());
        }
    }
}