force-app/main/default/objects/CNT_ApiConfiguration__c/CNT_ApiConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to handle api calls</description>
    <label>API Configuration</label>
</CustomObject>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>CNT_Endpoint__c</fullName>
    <description>Endpoint of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Endpoint of the service</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_HTTPMethod__c.field-meta.xml
<CustomField>
    <fullName>CNT_HTTPMethod__c</fullName>
    <description>Http Method of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Http Method of the service</inlineHelpText>
    <label>HTTP Method</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CNT_WRAPPERSWIFTPAYMENT.cls
/*----------------------------------------------------------------------------------
Author:         R. Alexander Cervino
Company:        Deloitte
Description:    Wrapper class to retrieve and give format to the swift payments
Test Class:     CNT_WRAPPERSWIFTPAYMENT_Test
History
<Date>			<Author>		<Description>
13/11/2019		R. Alexander Cervino     Initial version
----------------------------------------------------------------------------------*/
global with sharing class CNT_WRAPPERSWIFTPAYMENT{

    private String output;
    private String input;

    global String getOutput () {
        System.debug('devuelvo');
        System.debug(this.output);

        return this.output;
    }

    global CNT_WRAPPERSWIFTPAYMENT(String filters){
        this.input=filters;
    }
    
    global CNT_WRAPPERSWIFTPAYMENT(){
        System.debug('CNT_WRAPPERSWIFTPAYMENT');
    }

    /*----------------------------------------------------------------------------------
    Author:         R. Alexander Cervino
    Company:        Deloitte
    Description:    Method that retrieves the data from the input source
    History
    <Date>			<Author>		<Description>
    13/11/2019		R. Alexander Cervino     Initial version
    ----------------------------------------------------------------------------------*/
    global void execute(){
        try {
            String response = '';
            this.output = null;
            
            /*if(input!='' && input!='undefined' && input!=null && input=='status=Rejected'){
                response = Global_IntegrationWrapper.launchHttp('','https://e-onetrade.de-c1.cloudhub.io/api/payments_trackva nrizer?'+input,'GET');
            }else{
                response = Global_IntegrationWrapper.launchHttp('','https://e-onetrade.de-c1.cloudhub.io/api/payments_tracker','GET');
            }*/
            if(input!=''){
                CNT_ApiConfiguration__c configWs = CNT_ApiConfiguration__c.getValues('CNT_WRAPPERSWIFTPAYMENT');

                response = Global_IntegrationWrapper.launchHttp(input,configWs.CNT_Endpoint__c,configWs.CNT_HTTPMethod__c);
            }

            this.output = response;

        } catch (Exception e) {
            System.debug('execute.CNT_WRAPPERSWIFTPAYMENT: ' + e.getMessage());
			throw new customException(e.getMessage());
        }
    }
}