force-app/main/default/objects/CNT_ApiConfiguration__c/CNT_ApiConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to handle api calls</description>
    <label>API Configuration</label>
</CustomObject>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>CNT_Endpoint__c</fullName>
    <description>Endpoint of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Endpoint of the service</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_HTTPMethod__c.field-meta.xml
<CustomField>
    <fullName>CNT_HTTPMethod__c</fullName>
    <description>Http Method of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Http Method of the service</inlineHelpText>
    <label>HTTP Method</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

zip/mdapiOTVLwr/unpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>USER_TXT_GlobalId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Global Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/CALLOUT_PaymentsTrackerAsyncCallout.cls
/*----------------------------------------------------------------------------------
Author:         Guillermo Giral
Company:        Deloitte
Description:    
Test Class:     
History
<Date>          <Author>            <Description>
15/07/2020      Guillermo Giral     Initial version
----------------------------------------------------------------------------------*/
public class CALLOUT_PaymentsTrackerAsyncCallout implements Queueable, Database.AllowsCallouts {

    public final String globalId;

    /*----------------------------------------------------------------------------------
    Author:         Guillermo Giral
    Company:        Deloitte
    Description:    
    History
    <Date>          <Author>            <Description>
    15/07/2020      Guillermo Giral     Initial version
    ----------------------------------------------------------------------------------*/
    public void execute(QueueableContext context) {

        CNT_ApiConfiguration__c configWs = CNT_ApiConfiguration__c.getValues('CNT_BalanceLastUpdate');
        List<User> loggedUser = [SELECT Id, Username FROM User WHERE USER_TXT_GlobalId__c =: globalId];
        System.debug('Logged user: ' + loggedUser);
        if(!loggedUser.isEmpty()){
            String response = Global_IntegrationWrapper.launchHTTP('', configWs.CNT_Endpoint__c, configWs.CNT_HTTPMethod__c, null, loggedUser[0].Id, false);
        }
    }

    public CALLOUT_PaymentsTrackerAsyncCallout(String input){
        globalId = input;
    }
}