force-app/main/default/objects/CNT_ApiConfiguration__c/CNT_ApiConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to handle api calls</description>
    <label>API Configuration</label>
</CustomObject>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>CNT_Endpoint__c</fullName>
    <description>Endpoint of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Endpoint of the service</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_HTTPMethod__c.field-meta.xml
<CustomField>
    <fullName>CNT_HTTPMethod__c</fullName>
    <description>Http Method of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Http Method of the service</inlineHelpText>
    <label>HTTP Method</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_Service__c.field-meta.xml
<CustomField>
    <fullName>CNT_Service__c</fullName>
    <description>Service of the endpoint</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Service of the endpoint</inlineHelpText>
    <label>Service</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/tokenPlatform__c.field-meta.xml
<CustomField>
    <fullName>tokenPlatform__c</fullName>
    <description>Indicates if the platform is GTS or SANDIGITAL</description>
    <encryptionScheme>None</encryptionScheme>
    <label>tokenPlatform</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/tokenUser__c.field-meta.xml
<CustomField>
    <fullName>tokenUser__c</fullName>
    <description>Indicates if the user is nexus, local or platform</description>
    <encryptionScheme>None</encryptionScheme>
    <label>tokenUser</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/STR_SignatureRule__c/STR_SignatureRule__c.object-meta.xml
<CustomObject>
    <label>Signature Rule</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signature Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/STR_ServiceStructurals_Test.cls
/*----------------------------------------------------------------------------------
Author:         Andrea Martín
Company:        Deloitte
History
<Date>			<Author>		<Description>
01/03/2021		Andrea Martín     Initial version
----------------------------------------------------------------------------------*/
@isTest
public class STR_ServiceStructurals_Test {
    
    @TestSetup
    static void setup(){
        DataFactory.getCustomSettingCryptoKey(true);
        DataFactory.createWsConfigurationSetting(true); 

    }
     @isTest 
    static  void getRules_test(){
        try{
            CNT_ApiConfiguration__c configWs = new CNT_ApiConfiguration__c(
                Name = 'WS_STR_SignatureRules',
                CNT_Endpoint__c = 'https://api.sandbox.mulesoft.onetrade.santander.com/onetrade/cert/api/v1/gts_signature/rule',
                CNT_HTTPMethod__c = 'GET',
                tokenPlatform__c = 'GTS',
                tokenUser__c = 'local',
                CNT_Service__c = 'mulesoft'
            );
            insert configWs;
            
            Test.setMock(HttpCalloutMock.class, new WS_STR_SignatureRules_MockHttp.getRulesResponse());
            String companyId = '123';

            Test.startTest();
            STR_ServiceStructurals.getRules(companyId);
            Test.stopTest();          
            
        } catch (Exception e) {
            System.debug('STR_ServiceStructurals_Test.getRules_test: ' + e.getMessage() + ', in line: ' + e.getLineNumber());
        }
    }
       @isTest 
    static  void postRules_test(){
        try{
            CNT_ApiConfiguration__c configWs = new CNT_ApiConfiguration__c(
                Name = 'WS_STR_SignatureRules',
                CNT_Endpoint__c = 'https://api.sandbox.mulesoft.onetrade.santander.com/onetrade/cert/api/v1/gts_signature/rule',
                CNT_HTTPMethod__c = 'POST',
                tokenPlatform__c = 'GTS',
                tokenUser__c = 'local',
                CNT_Service__c = 'mulesoft'
            );
            insert configWs;
            Test.setMock(HttpCalloutMock.class, new WS_STR_SignatureRules_MockHttp.getRulesResponse());
             String companyId = '123';
            List<STR_SignatureRule__c> ruleList = new List<STR_SignatureRule__c>();

            String body = '';
            Test.startTest();
            STR_ServiceStructurals.postRules(companyId, ruleList);
            Test.stopTest();          
            
        } catch (Exception e) {
            System.debug('STR_ServiceStructurals_Test.postRules_test: ' + e.getMessage() + ', in line: ' + e.getLineNumber());
        }
    }
    
    @isTest 
    static  void patchRule_test(){
        try{
            CNT_ApiConfiguration__c configWs = new CNT_ApiConfiguration__c(
                Name = 'WS_STR_SignatureRules',
                CNT_Endpoint__c = 'https://api.sandbox.mulesoft.onetrade.santander.com/onetrade/cert/api/v1/gts_signature/rule',
                CNT_HTTPMethod__c = 'PATCH',
                tokenPlatform__c = 'GTS',
                tokenUser__c = 'local',
                CNT_Service__c = 'mulesoft'
            );
            insert configWs;
            
            Test.setMock(HttpCalloutMock.class, new WS_STR_SignatureRules_MockHttp.getRulesResponse());
			STR_SignatureRule__c rule = new STR_SignatureRule__c();
            Test.startTest();
            STR_ServiceStructurals.patchRule(rule);
            Test.stopTest();          
            
        } catch (Exception e) {
            System.debug('STR_ServiceStructurals_Test.patchRule_test: ' + e.getMessage() + ', in line: ' + e.getLineNumber());
        }
    }
        @isTest 
    static  void deleteRule_test(){
        try{
            CNT_ApiConfiguration__c configWs = new CNT_ApiConfiguration__c(
                Name = 'WS_STR_SignatureRules',
                CNT_Endpoint__c = 'https://api.sandbox.mulesoft.onetrade.santander.com/onetrade/cert/api/v1/gts_signature/rule',
                CNT_HTTPMethod__c = 'PATCH',
                tokenPlatform__c = 'GTS',
                tokenUser__c = 'local',
                CNT_Service__c = 'mulesoft'
            );
            insert configWs;
            
            Test.setMock(HttpCalloutMock.class, new WS_STR_SignatureRules_MockHttp.getRulesResponse());
			STR_SignatureRule__c rule = new STR_SignatureRule__c();
            Test.startTest();
            STR_ServiceStructurals.deleteRule(rule);
            Test.stopTest();          
            
        } catch (Exception e) {
            System.debug('STR_ServiceStructurals_Test.deleteRule_test: ' + e.getMessage() + ', in line: ' + e.getLineNumber());
        }
    }
    
}