force-app/main/default/objects/CNT_ApiConfiguration__c/CNT_ApiConfiguration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to handle api calls</description>
    <label>API Configuration</label>
</CustomObject>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>CNT_Endpoint__c</fullName>
    <description>Endpoint of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Endpoint of the service</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNT_ApiConfiguration__c/fields/CNT_HTTPMethod__c.field-meta.xml
<CustomField>
    <fullName>CNT_HTTPMethod__c</fullName>
    <description>Http Method of the service</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Http Method of the service</inlineHelpText>
    <label>HTTP Method</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WS_B2B_storeSignature.cls
global class WS_B2B_storeSignature {
    
    global static String statusCode;
    
    global WS_B2B_storeSignature(){}
    
	global class storeSignatureBody {
        global String operationGlobalId;
        global String globalUserId;
        global String scaId;
        global storeSignatureBody(String operationGlobalId, String scaId){
            this.operationGlobalId = operationGlobalId;
            this.globalUserId = Global_Utilities.getUserData('').USER_TXT_GlobalId__c;
            this.scaId = scaId;
        }
    }
    
    
    global static String storeSignature(String operationGlobalId, String scaId){
        try {
            CNT_ApiConfiguration__c configWs = CNT_ApiConfiguration__c.getValues('B2B_StoreSignature');
			String finalEndPoint = configWs.CNT_Endpoint__c;            
            if (!Test.isRunningTest()) {
                
                Map<String, String> extraHeader = new Map<String, String>();
                extraHeader.put('Global-Payment-Id', operationGlobalId);
                storeSignatureBody initBody = new storeSignatureBody(operationGlobalId, scaId);
                
                String res = Global_IntegrationWrapper.launchHTTP(JSON.serialize(initBody,true),finalEndPoint,configWs.CNT_HTTPMethod__c);
                return Global_IntegrationWrapper.statusCode;              
                //validateAccountOutput = (validateAccountOutput) System.JSON.deserialize(res, validateAccountOutput.class);
            }else{
                
                String json = '{'+
                    '    \"operationGlobalId\": \"00000001\",'+
                    '    \"operationGlobalId\": \"00000001\"'+
                    '  }';
                //validateAccountOutput = (validateAccountOutput) System.JSON.deserialize(json, validateAccountOutput.class);
            }
            
            return '';
            
        } catch (Exception e) {
            System.debug('storeSognature: ' + e.getMessage() + ', in line: ' + e.getLineNumber());

            throw new AuraHandledException('The following exception has occurred: ' + e.getMessage()); 
        }
    }
}